import type { AgentMessage, FileNode, Commit } from "@/types";

const f = (name: string, path: string, lang: string, code: string): FileNode =>
  ({ name, path, type: "file", language: lang, content: code });

const d = (name: string, path: string, children: FileNode[]): FileNode =>
  ({ name, path, type: "directory", children });

// Realistic agent messages that simulate building a blockchain
const DEMO_MESSAGES: Omit<AgentMessage, "id" | "timestamp">[] = [
  { agent: "Yami", turn: 1, content: "Decomposing prompt into micro-tasks. Analyzing requirements: block structure, SHA-256 hashing, chain validation, proof-of-work, transactions, digital signatures, P2P networking, CLI." },
  { agent: "Yami", turn: 2, content: "Created 32 micro-tasks with dependency graph. Routing to agents based on complexity scoring." },
  { agent: "Akira", turn: 3, content: "[claude-opus-4-6] Designing core architecture. Establishing module boundaries: /src/core, /src/crypto, /src/wallet, /src/network, /src/rpc, /src/mempool, /src/mining, /src/storage, /src/cli." },
  { agent: "Akira", turn: 4, content: "Defined TypeScript interfaces — Block, BlockHeader, Transaction, UTXO, Peer, NetworkMessage, WalletState, RPCRequest, MempoolEntry.", codeBlock: { filename: "src/types/block.ts", language: "typescript", code: `export interface BlockHeader {\n  version: number;\n  previousHash: string;\n  merkleRoot: string;\n  timestamp: number;\n  difficulty: number;\n  nonce: number;\n}\n\nexport interface Block {\n  header: BlockHeader;\n  transactions: Transaction[];\n  hash: string;\n  height: number;\n}\n\nexport interface Transaction {\n  id: string;\n  inputs: TransactionInput[];\n  outputs: TransactionOutput[];\n  timestamp: number;\n  fee: number;\n}` } },
  { agent: "Rei", turn: 5, content: "[claude-sonnet-4-6] Implementing SHA-256 hashing utilities, RIPEMD-160 address derivation, and Base58Check encoding." },
  { agent: "Rei", turn: 6, content: "Completed crypto module — double SHA-256 for block headers, merkle root computation, address generation from public keys.", codeBlock: { filename: "src/crypto/hash.ts", language: "typescript", code: `import { createHash } from "crypto";\n\nexport function sha256(data: string | Buffer): string {\n  return createHash("sha256").update(data).digest("hex");\n}\n\nexport function doubleSha256(data: string | Buffer): string {\n  const first = createHash("sha256").update(data).digest();\n  return createHash("sha256").update(first).digest("hex");\n}\n\nexport function ripemd160(data: Buffer): string {\n  return createHash("ripemd160").update(data).digest("hex");\n}\n\nexport function merkleRoot(hashes: string[]): string {\n  if (hashes.length === 0) return sha256("");\n  if (hashes.length === 1) return hashes[0];\n  const next: string[] = [];\n  for (let i = 0; i < hashes.length; i += 2) {\n    const left = hashes[i];\n    const right = hashes[i + 1] || left;\n    next.push(doubleSha256(left + right));\n  }\n  return merkleRoot(next);\n}` } },
  { agent: "Rei", turn: 7, content: "[claude-sonnet-4-6] Building ECDSA digital signature system with secp256k1 curve and address derivation." },
  { agent: "Rei", turn: 8, content: "Completed keys.ts and address.ts — key pair generation, message signing, signature verification, public key to address conversion.", codeBlock: { filename: "src/crypto/keys.ts", language: "typescript", code: `import { generateKeyPairSync, sign, verify, createECDH } from "crypto";\n\nexport interface KeyPair {\n  publicKey: string;\n  privateKey: string;\n  address: string;\n}\n\nexport function generateKeyPair(): KeyPair {\n  const ecdh = createECDH("secp256k1");\n  ecdh.generateKeys();\n  const { publicKey, privateKey } = generateKeyPairSync("ec", {\n    namedCurve: "secp256k1",\n    publicKeyEncoding: { type: "spki", format: "pem" },\n    privateKeyEncoding: { type: "pkcs8", format: "pem" },\n  });\n  return { publicKey, privateKey, address: deriveAddress(publicKey) };\n}` } },
  { agent: "Akira", turn: 9, content: "[claude-opus-4-6] Implementing Block class with header hashing, genesis block factory, serialization, and merkle tree integration." },
  { agent: "Rei", turn: 10, content: "Completed Block and genesis module — constructor, calculateHash(), createGenesis(), fromJSON(), toBuffer() methods.", codeBlock: { filename: "src/core/block.ts", language: "typescript", code: `import { doubleSha256, merkleRoot } from "../crypto/hash";\nimport type { Block, BlockHeader, Transaction } from "../types/block";\n\nexport class BlockImpl implements Block {\n  header: BlockHeader;\n  transactions: Transaction[];\n  hash: string;\n  height: number;\n\n  constructor(header: BlockHeader, txs: Transaction[], height: number) {\n    this.header = header;\n    this.transactions = txs;\n    this.height = height;\n    this.header.merkleRoot = merkleRoot(txs.map(t => t.id));\n    this.hash = this.calculateHash();\n  }\n\n  calculateHash(): string {\n    return doubleSha256(JSON.stringify(this.header));\n  }\n\n  static createGenesis(): BlockImpl {\n    return new BlockImpl({\n      version: 1, previousHash: "0".repeat(64),\n      merkleRoot: "0".repeat(64), timestamp: 1700000000000,\n      difficulty: 4, nonce: 0,\n    }, [], 0);\n  }\n}` } },
  { agent: "Rei", turn: 11, content: "[claude-sonnet-4-6] Implementing chain validation, difficulty adjustment algorithm, and chain reorganization logic." },
  { agent: "Rei", turn: 12, content: "Chain module complete — block addition, hash linkage verification, longest chain selection, difficulty retargeting every 2016 blocks." },
  { agent: "Akira", turn: 13, content: "[claude-opus-4-6] Implementing proof-of-work consensus with adjustable difficulty and parallel nonce search." },
  { agent: "Rei", turn: 14, content: "Proof-of-work miner complete — mining loop with hash target, difficulty adjustment, coinbase reward halving.", codeBlock: { filename: "src/mining/miner.ts", language: "typescript", code: `import { BlockImpl } from "../core/block";\nimport type { BlockHeader, Transaction } from "../types/block";\nimport { Mempool } from "../mempool/mempool";\n\nexport class Miner {\n  private mining = false;\n  private mempool: Mempool;\n  private difficulty: number;\n\n  constructor(mempool: Mempool, difficulty: number) {\n    this.mempool = mempool;\n    this.difficulty = difficulty;\n  }\n\n  mine(previousHash: string, height: number, minerAddress: string): BlockImpl {\n    const txs = this.mempool.selectTransactions(1_000_000);\n    const coinbase = this.createCoinbase(minerAddress, height);\n    const allTxs = [coinbase, ...txs];\n    const target = "0".repeat(this.difficulty);\n    let nonce = 0;\n\n    while (true) {\n      const header: BlockHeader = {\n        version: 1, previousHash, merkleRoot: "",\n        timestamp: Date.now(), difficulty: this.difficulty, nonce,\n      };\n      const block = new BlockImpl(header, allTxs, height);\n      if (block.hash.startsWith(target)) return block;\n      nonce++;\n    }\n  }\n}` } },
  { agent: "Rei", turn: 15, content: "[claude-sonnet-4-6] Building UTXO transaction system with fee calculation, coinbase rewards, and script validation." },
  { agent: "Rei", turn: 16, content: "Transaction system complete — UTXO tracking, input/output linking, fee estimation, double-spend prevention, serialization." },
  { agent: "Akira", turn: 17, content: "[claude-opus-4-6] Implementing wallet module — HD key derivation, UTXO scanning, balance calculation, transaction building." },
  { agent: "Rei", turn: 18, content: "Wallet complete — key storage, address generation, UTXO selection (largest-first), change output handling, transaction signing." },
  { agent: "Akira", turn: 19, content: "[claude-opus-4-6] Building mempool with fee-priority ordering, size limits, transaction validation, and eviction policy." },
  { agent: "Rei", turn: 20, content: "Mempool complete — priority queue by fee rate, 300MB size cap, orphan transaction tracking, replacement-by-fee support." },
  { agent: "Akira", turn: 21, content: "[claude-opus-4-6] Designing P2P networking layer — peer discovery, block propagation, transaction relay, compact block protocol." },
  { agent: "Rei", turn: 22, content: "P2P networking complete — WebSocket connections, handshake protocol, inv/getdata messaging, peer scoring, ban list.", codeBlock: { filename: "src/network/peer.ts", language: "typescript", code: `import WebSocket from "ws";\nimport type { NetworkMessage } from "../types/network";\n\nexport class Peer {\n  readonly address: string;\n  readonly ws: WebSocket;\n  private score: number = 100;\n  private lastSeen: number = Date.now();\n\n  constructor(address: string, ws: WebSocket) {\n    this.address = address;\n    this.ws = ws;\n    this.setupHandlers();\n  }\n\n  send(msg: NetworkMessage): void {\n    if (this.ws.readyState === WebSocket.OPEN) {\n      this.ws.send(JSON.stringify(msg));\n    }\n  }\n\n  penalize(amount: number): void {\n    this.score = Math.max(0, this.score - amount);\n  }\n\n  get isBanned(): boolean {\n    return this.score <= 0;\n  }\n}` } },
  { agent: "Akira", turn: 23, content: "[claude-opus-4-6] Implementing JSON-RPC server — getblock, gettransaction, sendrawtransaction, getbalance, getpeerinfo endpoints." },
  { agent: "Rei", turn: 24, content: "RPC server complete — HTTP JSON-RPC 2.0 interface, authentication, rate limiting, 12 endpoint handlers." },
  { agent: "Rei", turn: 25, content: "[claude-sonnet-4-6] Building LevelDB storage layer — block index, UTXO set persistence, chain state, write batches." },
  { agent: "Rei", turn: 26, content: "Storage layer complete — block storage, UTXO database, chain tip tracking, atomic writes, pruning support." },
  { agent: "Rei", turn: 27, content: "[claude-sonnet-4-6] Implementing CLI interface — node startup, mining control, wallet management, peer connections, RPC client." },
  { agent: "Kira", turn: 28, content: "[claude-sonnet-4-6] Writing unit tests for crypto module — 18 test cases covering SHA-256, ECDSA, merkle trees, address derivation." },
  { agent: "Kira", turn: 29, content: "All crypto tests passing. Coverage: hash functions, key generation, signing, verification, address encoding, edge cases." },
  { agent: "Kira", turn: 30, content: "[claude-sonnet-4-6] Running integration tests — full chain lifecycle: genesis → mine → transact → validate → reorg → sync." },
  { agent: "Kira", turn: 31, content: "Integration tests passing. Validated: block mining, mempool eviction, chain reorg, peer sync, wallet balance, RPC endpoints, double-spend rejection." },
  { agent: "Yami", turn: 32, content: "All 32 tasks complete. Blockchain implementation ready — 46 files, 4,218 lines, full P2P stack with wallet, RPC, and storage." },
];

// 46 files across a deep project structure
const DEMO_FILES: FileNode[] = [
  d("src", "src", [
    d("core", "src/core", [
      f("block.ts", "src/core/block.ts", "typescript", `import { doubleSha256, merkleRoot } from "../crypto/hash";\nimport type { Block, BlockHeader, Transaction } from "../types/block";\n\nexport class BlockImpl implements Block {\n  header: BlockHeader;\n  transactions: Transaction[];\n  hash: string;\n  height: number;\n\n  constructor(header: BlockHeader, txs: Transaction[], height: number) {\n    this.header = header;\n    this.transactions = txs;\n    this.height = height;\n    this.header.merkleRoot = merkleRoot(txs.map(t => t.id));\n    this.hash = this.calculateHash();\n  }\n\n  calculateHash(): string {\n    return doubleSha256(JSON.stringify(this.header));\n  }\n\n  static createGenesis(): BlockImpl {\n    return new BlockImpl({ version: 1, previousHash: "0".repeat(64), merkleRoot: "0".repeat(64), timestamp: 1700000000000, difficulty: 4, nonce: 0 }, [], 0);\n  }\n\n  toJSON(): object {\n    return { header: this.header, transactions: this.transactions, hash: this.hash, height: this.height };\n  }\n}`),
      f("blockchain.ts", "src/core/blockchain.ts", "typescript", `import { BlockImpl } from "./block";\nimport { validateProofOfWork } from "../mining/pow";\nimport { UTXOSet } from "../storage/utxo";\n\nexport class Blockchain {\n  chain: BlockImpl[];\n  difficulty: number;\n  utxoSet: UTXOSet;\n\n  constructor() {\n    this.chain = [BlockImpl.createGenesis()];\n    this.difficulty = 4;\n    this.utxoSet = new UTXOSet();\n  }\n\n  getLatestBlock(): BlockImpl { return this.chain[this.chain.length - 1]; }\n  getBlockByHash(hash: string): BlockImpl | undefined { return this.chain.find(b => b.hash === hash); }\n  getBlockByHeight(h: number): BlockImpl | undefined { return this.chain[h]; }\n\n  addBlock(block: BlockImpl): boolean {\n    if (!this.isValidBlock(block)) return false;\n    this.chain.push(block);\n    this.utxoSet.applyBlock(block);\n    if (this.chain.length % 2016 === 0) this.adjustDifficulty();\n    return true;\n  }\n\n  isValidBlock(block: BlockImpl): boolean {\n    const prev = this.getLatestBlock();\n    if (block.header.previousHash !== prev.hash) return false;\n    if (!validateProofOfWork(block.hash, this.difficulty)) return false;\n    return block.hash === block.calculateHash();\n  }\n\n  adjustDifficulty(): void {\n    const last2016 = this.chain.slice(-2016);\n    const timespan = last2016[last2016.length - 1].header.timestamp - last2016[0].header.timestamp;\n    const expected = 2016 * 600000;\n    if (timespan < expected / 4) this.difficulty++;\n    else if (timespan > expected * 4) this.difficulty = Math.max(1, this.difficulty - 1);\n  }\n\n  isValidChain(): boolean {\n    for (let i = 1; i < this.chain.length; i++) {\n      if (!this.isValidBlock(this.chain[i])) return false;\n    }\n    return true;\n  }\n}`),
      f("genesis.ts", "src/core/genesis.ts", "typescript", `import { BlockImpl } from "./block";\n\nexport const GENESIS_BLOCK = BlockImpl.createGenesis();\n\nexport const GENESIS_HASH = GENESIS_BLOCK.hash;\n\nexport const NETWORK_MAGIC = Buffer.from("f9beb4d9", "hex");\n\nexport const MAX_BLOCK_SIZE = 4_000_000;\nexport const COINBASE_MATURITY = 100;\nexport const HALVING_INTERVAL = 210_000;\nexport const INITIAL_REWARD = 50_00000000;\n\nexport function getBlockReward(height: number): number {\n  const halvings = Math.floor(height / HALVING_INTERVAL);\n  if (halvings >= 64) return 0;\n  return Math.floor(INITIAL_REWARD / Math.pow(2, halvings));\n}`),
    ]),
    d("crypto", "src/crypto", [
      f("hash.ts", "src/crypto/hash.ts", "typescript", `import { createHash } from "crypto";\n\nexport function sha256(data: string | Buffer): string {\n  return createHash("sha256").update(data).digest("hex");\n}\n\nexport function doubleSha256(data: string | Buffer): string {\n  const first = createHash("sha256").update(data).digest();\n  return createHash("sha256").update(first).digest("hex");\n}\n\nexport function ripemd160(data: Buffer): string {\n  return createHash("ripemd160").update(data).digest("hex");\n}\n\nexport function hash160(data: Buffer): string {\n  const s = createHash("sha256").update(data).digest();\n  return createHash("ripemd160").update(s).digest("hex");\n}\n\nexport function merkleRoot(hashes: string[]): string {\n  if (hashes.length === 0) return sha256("");\n  if (hashes.length === 1) return hashes[0];\n  const next: string[] = [];\n  for (let i = 0; i < hashes.length; i += 2) {\n    const left = hashes[i];\n    const right = hashes[i + 1] || left;\n    next.push(doubleSha256(left + right));\n  }\n  return merkleRoot(next);\n}`),
      f("keys.ts", "src/crypto/keys.ts", "typescript", `import { generateKeyPairSync, sign, verify, createECDH } from "crypto";\nimport { hash160 } from "./hash";\nimport { encodeBase58Check } from "./base58";\n\nexport interface KeyPair {\n  publicKey: string;\n  privateKey: string;\n  address: string;\n}\n\nexport function generateKeyPair(): KeyPair {\n  const ecdh = createECDH("secp256k1");\n  ecdh.generateKeys();\n  const { publicKey, privateKey } = generateKeyPairSync("ec", {\n    namedCurve: "secp256k1",\n    publicKeyEncoding: { type: "spki", format: "pem" },\n    privateKeyEncoding: { type: "pkcs8", format: "pem" },\n  });\n  const address = deriveAddress(publicKey);\n  return { publicKey, privateKey, address };\n}\n\nexport function deriveAddress(publicKey: string): string {\n  const h = hash160(Buffer.from(publicKey));\n  return encodeBase58Check(Buffer.from("00" + h, "hex"));\n}\n\nexport function signMessage(msg: string, key: string): string {\n  return sign("sha256", Buffer.from(msg), key).toString("hex");\n}\n\nexport function verifySignature(msg: string, sig: string, key: string): boolean {\n  return verify("sha256", Buffer.from(msg), key, Buffer.from(sig, "hex"));\n}`),
      f("base58.ts", "src/crypto/base58.ts", "typescript", `const ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";\n\nexport function encodeBase58(buffer: Buffer): string {\n  let num = BigInt("0x" + buffer.toString("hex"));\n  let result = "";\n  while (num > 0n) {\n    const remainder = num % 58n;\n    num = num / 58n;\n    result = ALPHABET[Number(remainder)] + result;\n  }\n  for (const byte of buffer) {\n    if (byte !== 0) break;\n    result = "1" + result;\n  }\n  return result;\n}\n\nexport function encodeBase58Check(payload: Buffer): string {\n  const { sha256 } = require("./hash");\n  const checksum = sha256(sha256(payload.toString("hex"))).slice(0, 8);\n  return encodeBase58(Buffer.concat([payload, Buffer.from(checksum, "hex")]));\n}\n\nexport function decodeBase58(str: string): Buffer {\n  let num = 0n;\n  for (const char of str) {\n    num = num * 58n + BigInt(ALPHABET.indexOf(char));\n  }\n  const hex = num.toString(16).padStart(2, "0");\n  return Buffer.from(hex, "hex");\n}`),
      f("address.ts", "src/crypto/address.ts", "typescript", `import { hash160 } from "./hash";\nimport { encodeBase58Check, decodeBase58 } from "./base58";\n\nexport enum AddressType {\n  P2PKH = 0x00,\n  P2SH = 0x05,\n  TESTNET = 0x6f,\n}\n\nexport function publicKeyToAddress(pubKey: Buffer, type: AddressType = AddressType.P2PKH): string {\n  const h = hash160(pubKey);\n  const payload = Buffer.alloc(21);\n  payload[0] = type;\n  Buffer.from(h, "hex").copy(payload, 1);\n  return encodeBase58Check(payload);\n}\n\nexport function isValidAddress(address: string): boolean {\n  try {\n    const decoded = decodeBase58(address);\n    return decoded.length >= 25;\n  } catch {\n    return false;\n  }\n}\n\nexport function getAddressType(address: string): AddressType | null {\n  const decoded = decodeBase58(address);\n  const version = decoded[0];\n  if (version === 0x00) return AddressType.P2PKH;\n  if (version === 0x05) return AddressType.P2SH;\n  if (version === 0x6f) return AddressType.TESTNET;\n  return null;\n}`),
    ]),
    d("wallet", "src/wallet", [
      f("wallet.ts", "src/wallet/wallet.ts", "typescript", `import { generateKeyPair, KeyPair, signMessage } from "../crypto/keys";\nimport { createTransaction, Transaction } from "../transaction/builder";\nimport type { UTXO } from "../types/transaction";\n\nexport class Wallet {\n  private keys: KeyPair;\n  private utxos: UTXO[] = [];\n\n  constructor(existingKey?: KeyPair) {\n    this.keys = existingKey || generateKeyPair();\n  }\n\n  get address(): string { return this.keys.address; }\n  get publicKey(): string { return this.keys.publicKey; }\n\n  getBalance(): number {\n    return this.utxos.reduce((sum, u) => sum + u.amount, 0);\n  }\n\n  updateUTXOs(utxos: UTXO[]): void {\n    this.utxos = utxos.filter(u => u.address === this.address);\n  }\n\n  createTransaction(to: string, amount: number, fee: number): Transaction {\n    const selected = this.selectUTXOs(amount + fee);\n    const change = selected.reduce((s, u) => s + u.amount, 0) - amount - fee;\n    return createTransaction(selected, to, amount, this.address, change, this.keys);\n  }\n\n  private selectUTXOs(target: number): UTXO[] {\n    const sorted = [...this.utxos].sort((a, b) => b.amount - a.amount);\n    const selected: UTXO[] = [];\n    let total = 0;\n    for (const utxo of sorted) {\n      selected.push(utxo);\n      total += utxo.amount;\n      if (total >= target) break;\n    }\n    if (total < target) throw new Error("Insufficient funds");\n    return selected;\n  }\n}`),
      f("keystore.ts", "src/wallet/keystore.ts", "typescript", `import { readFileSync, writeFileSync, existsSync } from "fs";\nimport { createCipheriv, createDecipheriv, randomBytes, scryptSync } from "crypto";\nimport type { KeyPair } from "../crypto/keys";\n\nexport class Keystore {\n  private path: string;\n\n  constructor(path: string) {\n    this.path = path;\n  }\n\n  save(keys: KeyPair, password: string): void {\n    const salt = randomBytes(16);\n    const key = scryptSync(password, salt, 32);\n    const iv = randomBytes(16);\n    const cipher = createCipheriv("aes-256-gcm", key, iv);\n    const data = JSON.stringify(keys);\n    const encrypted = Buffer.concat([cipher.update(data, "utf8"), cipher.final()]);\n    const tag = cipher.getAuthTag();\n    writeFileSync(this.path, JSON.stringify({\n      salt: salt.toString("hex"), iv: iv.toString("hex"),\n      tag: tag.toString("hex"), data: encrypted.toString("hex"),\n    }));\n  }\n\n  load(password: string): KeyPair {\n    const raw = JSON.parse(readFileSync(this.path, "utf8"));\n    const key = scryptSync(password, Buffer.from(raw.salt, "hex"), 32);\n    const decipher = createDecipheriv("aes-256-gcm", key, Buffer.from(raw.iv, "hex"));\n    decipher.setAuthTag(Buffer.from(raw.tag, "hex"));\n    const decrypted = decipher.update(raw.data, "hex", "utf8") + decipher.final("utf8");\n    return JSON.parse(decrypted);\n  }\n\n  exists(): boolean { return existsSync(this.path); }\n}`),
      f("hdkey.ts", "src/wallet/hdkey.ts", "typescript", `import { createHmac } from "crypto";\nimport { generateKeyPair } from "../crypto/keys";\n\nexport class HDKey {\n  private seed: Buffer;\n  private chainCode: Buffer;\n\n  constructor(mnemonic: string) {\n    this.seed = createHmac("sha512", "zyraos-seed").update(mnemonic).digest();\n    this.chainCode = this.seed.subarray(32);\n  }\n\n  deriveChild(index: number) {\n    const data = Buffer.alloc(37);\n    this.seed.subarray(0, 33).copy(data);\n    data.writeUInt32BE(index, 33);\n    const I = createHmac("sha512", this.chainCode).update(data).digest();\n    return { key: I.subarray(0, 32), chainCode: I.subarray(32) };\n  }\n\n  derivePath(path: string) {\n    const segments = path.split("/").slice(1);\n    let current = this;\n    for (const seg of segments) {\n      const idx = parseInt(seg.replace("'", ""));\n      current.deriveChild(idx);\n    }\n    return current;\n  }\n}`),
    ]),
    d("transaction", "src/transaction", [
      f("builder.ts", "src/transaction/builder.ts", "typescript", `import { sha256 } from "../crypto/hash";\nimport { signMessage } from "../crypto/keys";\nimport type { Transaction, TransactionInput, TransactionOutput, UTXO } from "../types/transaction";\nimport type { KeyPair } from "../crypto/keys";\n\nexport type { Transaction };\n\nexport function createTransaction(\n  utxos: UTXO[], to: string, amount: number,\n  changeAddress: string, change: number, keys: KeyPair\n): Transaction {\n  const inputs: TransactionInput[] = utxos.map(u => ({\n    txId: u.txId, outputIndex: u.outputIndex,\n    signature: "", publicKey: keys.publicKey,\n  }));\n  const outputs: TransactionOutput[] = [\n    { address: to, amount },\n    ...(change > 0 ? [{ address: changeAddress, amount: change }] : []),\n  ];\n  const tx: Transaction = { id: "", inputs, outputs, timestamp: Date.now(), fee: 0 };\n  tx.id = sha256(JSON.stringify({ inputs, outputs, timestamp: tx.timestamp }));\n  tx.inputs = tx.inputs.map(i => ({ ...i, signature: signMessage(tx.id, keys.privateKey) }));\n  tx.fee = utxos.reduce((s, u) => s + u.amount, 0) - amount - change;\n  return tx;\n}`),
      f("validator.ts", "src/transaction/validator.ts", "typescript", `import { verifySignature } from "../crypto/keys";\nimport type { Transaction } from "../types/transaction";\nimport type { UTXOSet } from "../storage/utxo";\n\nexport function validateTransaction(tx: Transaction, utxoSet: UTXOSet): { valid: boolean; error?: string } {\n  if (tx.inputs.length === 0) return { valid: false, error: "No inputs" };\n  if (tx.outputs.length === 0) return { valid: false, error: "No outputs" };\n\n  let inputTotal = 0;\n  for (const input of tx.inputs) {\n    const utxo = utxoSet.get(input.txId, input.outputIndex);\n    if (!utxo) return { valid: false, error: "UTXO not found: " + input.txId };\n    if (!verifySignature(tx.id, input.signature, input.publicKey)) {\n      return { valid: false, error: "Invalid signature" };\n    }\n    inputTotal += utxo.amount;\n  }\n\n  const outputTotal = tx.outputs.reduce((s, o) => s + o.amount, 0);\n  if (outputTotal > inputTotal) return { valid: false, error: "Outputs exceed inputs" };\n  if (tx.outputs.some(o => o.amount < 0)) return { valid: false, error: "Negative output" };\n\n  return { valid: true };\n}`),
      f("coinbase.ts", "src/transaction/coinbase.ts", "typescript", `import { sha256 } from "../crypto/hash";\nimport { getBlockReward } from "../core/genesis";\nimport type { Transaction } from "../types/transaction";\n\nexport function createCoinbaseTransaction(minerAddress: string, height: number, fees: number): Transaction {\n  const reward = getBlockReward(height);\n  const tx: Transaction = {\n    id: "",\n    inputs: [{ txId: "0".repeat(64), outputIndex: 0xffffffff, signature: \`coinbase:\${height}\`, publicKey: "" }],\n    outputs: [{ address: minerAddress, amount: reward + fees }],\n    timestamp: Date.now(),\n    fee: 0,\n  };\n  tx.id = sha256(JSON.stringify(tx.inputs) + JSON.stringify(tx.outputs) + height);\n  return tx;\n}`),
      f("serializer.ts", "src/transaction/serializer.ts", "typescript", `import type { Transaction } from "../types/transaction";\n\nexport function serializeTransaction(tx: Transaction): Buffer {\n  const json = JSON.stringify(tx);\n  const buf = Buffer.alloc(4 + json.length);\n  buf.writeUInt32LE(json.length, 0);\n  buf.write(json, 4);\n  return buf;\n}\n\nexport function deserializeTransaction(buf: Buffer): Transaction {\n  const len = buf.readUInt32LE(0);\n  const json = buf.subarray(4, 4 + len).toString();\n  return JSON.parse(json);\n}\n\nexport function calculateTxSize(tx: Transaction): number {\n  return serializeTransaction(tx).length;\n}\n\nexport function calculateFeeRate(tx: Transaction): number {\n  const size = calculateTxSize(tx);\n  return tx.fee / size;\n}`),
    ]),
    d("mining", "src/mining", [
      f("miner.ts", "src/mining/miner.ts", "typescript", `import { BlockImpl } from "../core/block";\nimport type { BlockHeader } from "../types/block";\nimport { Mempool } from "../mempool/mempool";\nimport { createCoinbaseTransaction } from "../transaction/coinbase";\n\nexport class Miner {\n  private mempool: Mempool;\n  private difficulty: number;\n  private hashRate: number = 0;\n\n  constructor(mempool: Mempool, difficulty: number) {\n    this.mempool = mempool;\n    this.difficulty = difficulty;\n  }\n\n  mine(previousHash: string, height: number, minerAddress: string): BlockImpl {\n    const txs = this.mempool.selectTransactions(4_000_000);\n    const fees = txs.reduce((s, t) => s + t.fee, 0);\n    const coinbase = createCoinbaseTransaction(minerAddress, height, fees);\n    const target = "0".repeat(this.difficulty);\n    let nonce = 0;\n    const start = Date.now();\n\n    while (true) {\n      const header: BlockHeader = {\n        version: 1, previousHash, merkleRoot: "",\n        timestamp: Date.now(), difficulty: this.difficulty, nonce,\n      };\n      const block = new BlockImpl(header, [coinbase, ...txs], height);\n      if (block.hash.startsWith(target)) {\n        this.hashRate = nonce / ((Date.now() - start) / 1000);\n        return block;\n      }\n      nonce++;\n    }\n  }\n\n  getHashRate(): number { return this.hashRate; }\n}`),
      f("pow.ts", "src/mining/pow.ts", "typescript", `export function validateProofOfWork(hash: string, difficulty: number): boolean {\n  return hash.startsWith("0".repeat(difficulty));\n}\n\nexport function calculateTarget(difficulty: number): string {\n  return "0".repeat(difficulty) + "f".repeat(64 - difficulty);\n}\n\nexport function compareDifficulty(hash: string, target: string): boolean {\n  return BigInt("0x" + hash) <= BigInt("0x" + target);\n}`),
      f("difficulty.ts", "src/mining/difficulty.ts", "typescript", `export const TARGET_BLOCK_TIME = 600_000;\nexport const ADJUSTMENT_INTERVAL = 2016;\n\nexport function adjustDifficulty(currentDifficulty: number, timestamps: number[]): number {\n  if (timestamps.length < ADJUSTMENT_INTERVAL) return currentDifficulty;\n  const actualTime = timestamps[timestamps.length - 1] - timestamps[0];\n  const expectedTime = ADJUSTMENT_INTERVAL * TARGET_BLOCK_TIME;\n  const ratio = actualTime / expectedTime;\n\n  if (ratio < 0.25) return currentDifficulty + 1;\n  if (ratio > 4.0) return Math.max(1, currentDifficulty - 1);\n  return currentDifficulty;\n}`),
    ]),
    d("mempool", "src/mempool", [
      f("mempool.ts", "src/mempool/mempool.ts", "typescript", `import type { Transaction } from "../types/transaction";\nimport { calculateFeeRate } from "../transaction/serializer";\n\ninterface MempoolEntry {\n  tx: Transaction;\n  addedAt: number;\n  feeRate: number;\n}\n\nexport class Mempool {\n  private entries: Map<string, MempoolEntry> = new Map();\n  private maxSize = 300_000_000;\n  private currentSize = 0;\n\n  add(tx: Transaction): boolean {\n    if (this.entries.has(tx.id)) return false;\n    const feeRate = calculateFeeRate(tx);\n    this.entries.set(tx.id, { tx, addedAt: Date.now(), feeRate });\n    this.currentSize += JSON.stringify(tx).length;\n    if (this.currentSize > this.maxSize) this.evict();\n    return true;\n  }\n\n  remove(txId: string): void { this.entries.delete(txId); }\n  has(txId: string): boolean { return this.entries.has(txId); }\n  get size(): number { return this.entries.size; }\n\n  selectTransactions(maxSize: number): Transaction[] {\n    const sorted = [...this.entries.values()].sort((a, b) => b.feeRate - a.feeRate);\n    const selected: Transaction[] = [];\n    let size = 0;\n    for (const entry of sorted) {\n      const txSize = JSON.stringify(entry.tx).length;\n      if (size + txSize > maxSize) break;\n      selected.push(entry.tx);\n      size += txSize;\n    }\n    return selected;\n  }\n\n  private evict(): void {\n    const sorted = [...this.entries.entries()].sort((a, b) => a[1].feeRate - b[1].feeRate);\n    while (this.currentSize > this.maxSize * 0.75 && sorted.length > 0) {\n      const [id] = sorted.shift()!;\n      this.entries.delete(id);\n    }\n  }\n}`),
      f("orphans.ts", "src/mempool/orphans.ts", "typescript", `import type { Transaction } from "../types/transaction";\n\nexport class OrphanPool {\n  private orphans: Map<string, Transaction> = new Map();\n  private maxSize = 1000;\n\n  add(tx: Transaction): void {\n    if (this.orphans.size >= this.maxSize) {\n      const oldest = this.orphans.keys().next().value;\n      if (oldest) this.orphans.delete(oldest);\n    }\n    this.orphans.set(tx.id, tx);\n  }\n\n  getByParent(txId: string): Transaction[] {\n    return [...this.orphans.values()].filter(tx =>\n      tx.inputs.some(i => i.txId === txId)\n    );\n  }\n\n  remove(txId: string): void { this.orphans.delete(txId); }\n  get size(): number { return this.orphans.size; }\n}`),
    ]),
    d("network", "src/network", [
      f("server.ts", "src/network/server.ts", "typescript", `import WebSocket from "ws";\nimport { Peer } from "./peer";\nimport { MessageHandler } from "./messages";\nimport type { NetworkMessage } from "../types/network";\n\nexport class P2PServer {\n  private peers: Map<string, Peer> = new Map();\n  private server: WebSocket.Server | null = null;\n  private handler: MessageHandler;\n\n  constructor(handler: MessageHandler) {\n    this.handler = handler;\n  }\n\n  start(port: number): void {\n    this.server = new WebSocket.Server({ port });\n    this.server.on("connection", (ws, req) => {\n      const addr = req.socket.remoteAddress + ":" + req.socket.remotePort;\n      this.addPeer(addr, ws);\n    });\n  }\n\n  connectTo(address: string): void {\n    const ws = new WebSocket(\`ws://\${address}\`);\n    ws.on("open", () => this.addPeer(address, ws));\n  }\n\n  broadcast(msg: NetworkMessage): void {\n    this.peers.forEach(p => p.send(msg));\n  }\n\n  private addPeer(addr: string, ws: WebSocket): void {\n    const peer = new Peer(addr, ws);\n    this.peers.set(addr, peer);\n    ws.on("message", (data) => this.handler.handle(JSON.parse(data.toString()), peer));\n    ws.on("close", () => this.peers.delete(addr));\n  }\n\n  getPeerCount(): number { return this.peers.size; }\n  getPeers(): Peer[] { return [...this.peers.values()]; }\n}`),
      f("peer.ts", "src/network/peer.ts", "typescript", `import WebSocket from "ws";\nimport type { NetworkMessage } from "../types/network";\n\nexport class Peer {\n  readonly address: string;\n  readonly ws: WebSocket;\n  private score: number = 100;\n  private lastSeen: number = Date.now();\n  private version: string = "unknown";\n\n  constructor(address: string, ws: WebSocket) {\n    this.address = address;\n    this.ws = ws;\n  }\n\n  send(msg: NetworkMessage): void {\n    if (this.ws.readyState === WebSocket.OPEN) {\n      this.ws.send(JSON.stringify(msg));\n      this.lastSeen = Date.now();\n    }\n  }\n\n  penalize(amount: number): void { this.score = Math.max(0, this.score - amount); }\n  reward(amount: number): void { this.score = Math.min(200, this.score + amount); }\n  get isBanned(): boolean { return this.score <= 0; }\n  get isStale(): boolean { return Date.now() - this.lastSeen > 300_000; }\n  setVersion(v: string): void { this.version = v; }\n}`),
      f("messages.ts", "src/network/messages.ts", "typescript", `import type { NetworkMessage } from "../types/network";\nimport { Peer } from "./peer";\nimport type { Blockchain } from "../core/blockchain";\nimport type { Mempool } from "../mempool/mempool";\n\nexport class MessageHandler {\n  private chain: Blockchain;\n  private mempool: Mempool;\n\n  constructor(chain: Blockchain, mempool: Mempool) {\n    this.chain = chain;\n    this.mempool = mempool;\n  }\n\n  handle(msg: NetworkMessage, from: Peer): void {\n    switch (msg.type) {\n      case "BLOCK": this.handleBlock(msg.payload, from); break;\n      case "TX": this.handleTransaction(msg.payload, from); break;\n      case "SYNC_REQUEST": this.handleSyncRequest(msg.payload, from); break;\n      case "SYNC_RESPONSE": this.handleSyncResponse(msg.payload, from); break;\n      case "PEERS": this.handlePeers(msg.payload, from); break;\n      case "PING": from.send({ type: "PONG", payload: null }); break;\n      default: from.penalize(10);\n    }\n  }\n\n  private handleBlock(block: any, from: Peer): void {\n    if (this.chain.addBlock(block)) from.reward(1);\n    else from.penalize(5);\n  }\n\n  private handleTransaction(tx: any, from: Peer): void {\n    this.mempool.add(tx);\n  }\n\n  private handleSyncRequest(payload: any, from: Peer): void {\n    const blocks = this.chain.chain.slice(payload.fromHeight);\n    from.send({ type: "SYNC_RESPONSE", payload: blocks });\n  }\n\n  private handleSyncResponse(blocks: any[], from: Peer): void {\n    for (const block of blocks) this.chain.addBlock(block);\n  }\n\n  private handlePeers(_peers: any[], _from: Peer): void {}\n}`),
      f("discovery.ts", "src/network/discovery.ts", "typescript", `import { P2PServer } from "./server";\n\nconst SEED_NODES = [\n  "seed1.zyraos.net:6001",\n  "seed2.zyraos.net:6001",\n  "seed3.zyraos.net:6001",\n];\n\nexport class PeerDiscovery {\n  private server: P2PServer;\n  private known: Set<string> = new Set();\n  private maxPeers = 125;\n\n  constructor(server: P2PServer) {\n    this.server = server;\n  }\n\n  async bootstrap(): Promise<void> {\n    for (const seed of SEED_NODES) {\n      if (this.server.getPeerCount() >= this.maxPeers) break;\n      try { this.server.connectTo(seed); this.known.add(seed); }\n      catch { /* seed unavailable */ }\n    }\n  }\n\n  addKnown(address: string): void { this.known.add(address); }\n  getKnown(): string[] { return [...this.known]; }\n}`),
    ]),
    d("rpc", "src/rpc", [
      f("server.ts", "src/rpc/server.ts", "typescript", `import { createServer, IncomingMessage, ServerResponse } from "http";\nimport { handleRPC } from "./handlers";\nimport type { Blockchain } from "../core/blockchain";\nimport type { Mempool } from "../mempool/mempool";\n\nexport function startRPCServer(chain: Blockchain, mempool: Mempool, port: number): void {\n  const server = createServer((req: IncomingMessage, res: ServerResponse) => {\n    if (req.method !== "POST") {\n      res.writeHead(405).end();\n      return;\n    }\n    let body = "";\n    req.on("data", (chunk) => body += chunk);\n    req.on("end", () => {\n      try {\n        const request = JSON.parse(body);\n        const result = handleRPC(request, chain, mempool);\n        res.writeHead(200, { "Content-Type": "application/json" });\n        res.end(JSON.stringify({ jsonrpc: "2.0", id: request.id, result }));\n      } catch (err: any) {\n        res.writeHead(200, { "Content-Type": "application/json" });\n        res.end(JSON.stringify({ jsonrpc: "2.0", id: null, error: { code: -32600, message: err.message } }));\n      }\n    });\n  });\n  server.listen(port);\n}`),
      f("handlers.ts", "src/rpc/handlers.ts", "typescript", `import type { Blockchain } from "../core/blockchain";\nimport type { Mempool } from "../mempool/mempool";\n\ninterface RPCRequest {\n  method: string;\n  params: any[];\n  id: number;\n}\n\nexport function handleRPC(req: RPCRequest, chain: Blockchain, mempool: Mempool): any {\n  switch (req.method) {\n    case "getblockcount": return chain.chain.length;\n    case "getbestblockhash": return chain.getLatestBlock().hash;\n    case "getblock": return chain.getBlockByHash(req.params[0])?.toJSON();\n    case "getblockbyheight": return chain.getBlockByHeight(req.params[0])?.toJSON();\n    case "getmempoolinfo": return { size: mempool.size };\n    case "getdifficulty": return chain.difficulty;\n    case "sendrawtransaction": {\n      const tx = req.params[0];\n      mempool.add(tx);\n      return tx.id;\n    }\n    case "getpeerinfo": return { peers: 0 };\n    case "validatechain": return chain.isValidChain();\n    default: throw new Error("Method not found: " + req.method);\n  }\n}`),
    ]),
    d("storage", "src/storage", [
      f("utxo.ts", "src/storage/utxo.ts", "typescript", `import type { BlockImpl } from "../core/block";\nimport type { UTXO } from "../types/transaction";\n\nexport class UTXOSet {\n  private utxos: Map<string, UTXO> = new Map();\n\n  private key(txId: string, index: number): string {\n    return \`\${txId}:\${index}\`;\n  }\n\n  add(utxo: UTXO): void {\n    this.utxos.set(this.key(utxo.txId, utxo.outputIndex), utxo);\n  }\n\n  remove(txId: string, index: number): void {\n    this.utxos.delete(this.key(txId, index));\n  }\n\n  get(txId: string, index: number): UTXO | undefined {\n    return this.utxos.get(this.key(txId, index));\n  }\n\n  getByAddress(address: string): UTXO[] {\n    return [...this.utxos.values()].filter(u => u.address === address);\n  }\n\n  applyBlock(block: BlockImpl): void {\n    for (const tx of block.transactions) {\n      for (const input of tx.inputs) {\n        this.remove(input.txId, input.outputIndex);\n      }\n      tx.outputs.forEach((output, i) => {\n        this.add({ txId: tx.id, outputIndex: i, address: output.address, amount: output.amount });\n      });\n    }\n  }\n\n  get size(): number { return this.utxos.size; }\n}`),
      f("blockstore.ts", "src/storage/blockstore.ts", "typescript", `import type { BlockImpl } from "../core/block";\n\nexport class BlockStore {\n  private blocks: Map<string, BlockImpl> = new Map();\n  private heightIndex: Map<number, string> = new Map();\n\n  put(block: BlockImpl): void {\n    this.blocks.set(block.hash, block);\n    this.heightIndex.set(block.height, block.hash);\n  }\n\n  getByHash(hash: string): BlockImpl | undefined {\n    return this.blocks.get(hash);\n  }\n\n  getByHeight(height: number): BlockImpl | undefined {\n    const hash = this.heightIndex.get(height);\n    return hash ? this.blocks.get(hash) : undefined;\n  }\n\n  getLatestHeight(): number {\n    return Math.max(...this.heightIndex.keys(), 0);\n  }\n\n  has(hash: string): boolean { return this.blocks.has(hash); }\n  get size(): number { return this.blocks.size; }\n}`),
      f("chainstate.ts", "src/storage/chainstate.ts", "typescript", `export interface ChainState {\n  bestBlockHash: string;\n  bestHeight: number;\n  totalWork: bigint;\n  chainId: string;\n}\n\nexport class ChainStateManager {\n  private state: ChainState;\n\n  constructor() {\n    this.state = {\n      bestBlockHash: "0".repeat(64),\n      bestHeight: 0,\n      totalWork: 0n,\n      chainId: "zyraos-mainnet",\n    };\n  }\n\n  update(hash: string, height: number, work: bigint): void {\n    this.state.bestBlockHash = hash;\n    this.state.bestHeight = height;\n    this.state.totalWork += work;\n  }\n\n  get(): ChainState { return { ...this.state }; }\n  get bestHeight(): number { return this.state.bestHeight; }\n  get bestHash(): string { return this.state.bestBlockHash; }\n}`),
    ]),
    d("types", "src/types", [
      f("block.ts", "src/types/block.ts", "typescript", `export interface BlockHeader {\n  version: number;\n  previousHash: string;\n  merkleRoot: string;\n  timestamp: number;\n  difficulty: number;\n  nonce: number;\n}\n\nexport interface Block {\n  header: BlockHeader;\n  transactions: Transaction[];\n  hash: string;\n  height: number;\n}\n\nexport interface Transaction {\n  id: string;\n  inputs: TransactionInput[];\n  outputs: TransactionOutput[];\n  timestamp: number;\n  fee: number;\n}\n\nexport interface TransactionInput {\n  txId: string;\n  outputIndex: number;\n  signature: string;\n  publicKey: string;\n}\n\nexport interface TransactionOutput {\n  address: string;\n  amount: number;\n}`),
      f("transaction.ts", "src/types/transaction.ts", "typescript", `export type { Transaction, TransactionInput, TransactionOutput } from "./block";\n\nexport interface UTXO {\n  txId: string;\n  outputIndex: number;\n  address: string;\n  amount: number;\n}\n\nexport interface MempoolEntry {\n  tx: Transaction;\n  addedAt: number;\n  feeRate: number;\n  size: number;\n}`),
      f("network.ts", "src/types/network.ts", "typescript", `import type { Block, Transaction } from "./block";\n\nexport interface Peer {\n  address: string;\n  port: number;\n  lastSeen: number;\n  version: string;\n  score: number;\n}\n\nexport type NetworkMessage =\n  | { type: "BLOCK"; payload: Block }\n  | { type: "TX"; payload: Transaction }\n  | { type: "PEERS"; payload: Peer[] }\n  | { type: "SYNC_REQUEST"; payload: { fromHeight: number } }\n  | { type: "SYNC_RESPONSE"; payload: Block[] }\n  | { type: "PING"; payload: null }\n  | { type: "PONG"; payload: null }\n  | { type: "INV"; payload: { type: string; hash: string }[] }\n  | { type: "GETDATA"; payload: { type: string; hash: string }[] };`),
      f("config.ts", "src/types/config.ts", "typescript", `export interface NodeConfig {\n  network: "mainnet" | "testnet";\n  port: number;\n  rpcPort: number;\n  dataDir: string;\n  maxPeers: number;\n  miningEnabled: boolean;\n  minerAddress?: string;\n  logLevel: "debug" | "info" | "warn" | "error";\n  seedNodes: string[];\n}`),
    ]),
    d("cli", "src/cli", [
      f("index.ts", "src/cli/index.ts", "typescript", `import { Blockchain } from "../core/blockchain";\nimport { generateKeyPair } from "../crypto/keys";\nimport { P2PServer } from "../network/server";\nimport { MessageHandler } from "../network/messages";\nimport { PeerDiscovery } from "../network/discovery";\nimport { Mempool } from "../mempool/mempool";\nimport { Miner } from "../mining/miner";\nimport { startRPCServer } from "../rpc/server";\nimport { parseArgs } from "./args";\n\nconst args = parseArgs();\nconst chain = new Blockchain();\nconst mempool = new Mempool();\nconst keys = generateKeyPair();\nconst handler = new MessageHandler(chain, mempool);\nconst server = new P2PServer(handler);\nconst discovery = new PeerDiscovery(server);\n\nconsole.log("ZyraOS Blockchain Node v1.0.0");\nconsole.log("Address:", keys.address);\nconsole.log("Chain height:", chain.chain.length);\n\nserver.start(args.port || 6001);\nstartRPCServer(chain, mempool, args.rpcPort || 8332);\ndiscovery.bootstrap();\n\nif (args.mine) {\n  const miner = new Miner(mempool, chain.difficulty);\n  console.log("Mining enabled. Target difficulty:", chain.difficulty);\n}`),
      f("args.ts", "src/cli/args.ts", "typescript", `export interface CLIArgs {\n  port: number;\n  rpcPort: number;\n  mine: boolean;\n  connect?: string;\n  dataDir: string;\n}\n\nexport function parseArgs(): CLIArgs {\n  const args = process.argv.slice(2);\n  const result: CLIArgs = {\n    port: 6001, rpcPort: 8332, mine: false, dataDir: "./data",\n  };\n\n  for (let i = 0; i < args.length; i++) {\n    switch (args[i]) {\n      case "--port": result.port = parseInt(args[++i]); break;\n      case "--rpc-port": result.rpcPort = parseInt(args[++i]); break;\n      case "--mine": result.mine = true; break;\n      case "--connect": result.connect = args[++i]; break;\n      case "--datadir": result.dataDir = args[++i]; break;\n    }\n  }\n  return result;\n}`),
    ]),
  ]),
  d("tests", "tests", [
    f("crypto.test.ts", "tests/crypto.test.ts", "typescript", `import { sha256, doubleSha256, merkleRoot, hash160 } from "../src/crypto/hash";\nimport { generateKeyPair, signMessage, verifySignature } from "../src/crypto/keys";\nimport { encodeBase58, encodeBase58Check } from "../src/crypto/base58";\n\ndescribe("SHA-256", () => {\n  test("produces 64-char hex", () => expect(sha256("hello")).toHaveLength(64));\n  test("double hash differs", () => expect(doubleSha256("hello")).not.toBe(sha256("hello")));\n  test("merkle root of empty", () => expect(merkleRoot([])).toBeTruthy());\n  test("merkle root of one", () => expect(merkleRoot(["abc"])).toBe("abc"));\n  test("hash160 produces 40-char hex", () => expect(hash160(Buffer.from("test"))).toHaveLength(40));\n});\n\ndescribe("ECDSA", () => {\n  test("sign and verify", () => {\n    const kp = generateKeyPair();\n    const sig = signMessage("test", kp.privateKey);\n    expect(verifySignature("test", sig, kp.publicKey)).toBe(true);\n  });\n  test("reject wrong key", () => {\n    const kp1 = generateKeyPair();\n    const kp2 = generateKeyPair();\n    const sig = signMessage("test", kp1.privateKey);\n    expect(verifySignature("test", sig, kp2.publicKey)).toBe(false);\n  });\n});\n\ndescribe("Base58", () => {\n  test("encodes buffer", () => expect(encodeBase58(Buffer.from("hello"))).toBeTruthy());\n});`),
    f("chain.test.ts", "tests/chain.test.ts", "typescript", `import { Blockchain } from "../src/core/blockchain";\n\ndescribe("Blockchain", () => {\n  test("starts with genesis block", () => {\n    const chain = new Blockchain();\n    expect(chain.chain).toHaveLength(1);\n    expect(chain.chain[0].height).toBe(0);\n  });\n  test("validates chain integrity", () => {\n    const chain = new Blockchain();\n    expect(chain.isValidChain()).toBe(true);\n  });\n  test("rejects invalid block", () => {\n    const chain = new Blockchain();\n    expect(chain.chain.length).toBe(1);\n  });\n});`),
    f("transaction.test.ts", "tests/transaction.test.ts", "typescript", `import { createCoinbaseTransaction } from "../src/transaction/coinbase";\nimport { serializeTransaction, deserializeTransaction } from "../src/transaction/serializer";\n\ndescribe("Coinbase Transaction", () => {\n  test("creates valid coinbase", () => {\n    const tx = createCoinbaseTransaction("addr123", 0, 0);\n    expect(tx.id).toBeTruthy();\n    expect(tx.outputs[0].amount).toBeGreaterThan(0);\n  });\n});\n\ndescribe("Serialization", () => {\n  test("roundtrip", () => {\n    const tx = createCoinbaseTransaction("addr123", 0, 0);\n    const buf = serializeTransaction(tx);\n    const decoded = deserializeTransaction(buf);\n    expect(decoded.id).toBe(tx.id);\n  });\n});`),
    f("mempool.test.ts", "tests/mempool.test.ts", "typescript", `import { Mempool } from "../src/mempool/mempool";\n\ndescribe("Mempool", () => {\n  test("adds and retrieves transactions", () => {\n    const pool = new Mempool();\n    const tx = { id: "tx1", inputs: [], outputs: [], timestamp: Date.now(), fee: 1000 };\n    expect(pool.add(tx as any)).toBe(true);\n    expect(pool.size).toBe(1);\n    expect(pool.has("tx1")).toBe(true);\n  });\n  test("rejects duplicates", () => {\n    const pool = new Mempool();\n    const tx = { id: "tx1", inputs: [], outputs: [], timestamp: Date.now(), fee: 1000 };\n    pool.add(tx as any);\n    expect(pool.add(tx as any)).toBe(false);\n  });\n  test("selects by fee rate", () => {\n    const pool = new Mempool();\n    pool.add({ id: "low", inputs: [], outputs: [], timestamp: Date.now(), fee: 100 } as any);\n    pool.add({ id: "high", inputs: [], outputs: [], timestamp: Date.now(), fee: 10000 } as any);\n    const selected = pool.selectTransactions(100000);\n    expect(selected[0].id).toBe("high");\n  });\n});`),
    f("wallet.test.ts", "tests/wallet.test.ts", "typescript", `import { Wallet } from "../src/wallet/wallet";\n\ndescribe("Wallet", () => {\n  test("generates address", () => {\n    const wallet = new Wallet();\n    expect(wallet.address).toBeTruthy();\n  });\n  test("starts with zero balance", () => {\n    const wallet = new Wallet();\n    expect(wallet.getBalance()).toBe(0);\n  });\n});`),
    f("network.test.ts", "tests/network.test.ts", "typescript", `import { Peer } from "../src/network/peer";\n\ndescribe("Peer", () => {\n  test("bans after penalties", () => {\n    const mockWs = { readyState: 1, send: jest.fn() } as any;\n    const peer = new Peer("127.0.0.1:6001", mockWs);\n    expect(peer.isBanned).toBe(false);\n    peer.penalize(100);\n    expect(peer.isBanned).toBe(true);\n  });\n});`),
  ]),
  f("package.json", "package.json", "json", `{\n  "name": "zyraos-blockchain",\n  "version": "1.0.0",\n  "description": "A blockchain built from scratch by ZyraOS agents",\n  "scripts": {\n    "build": "tsc",\n    "start": "node dist/cli/index.js",\n    "dev": "ts-node src/cli/index.ts",\n    "test": "jest --coverage",\n    "mine": "ts-node src/cli/index.ts --mine",\n    "lint": "eslint src/ --ext .ts"\n  },\n  "dependencies": {\n    "ws": "^8.16.0",\n    "leveldown": "^6.1.0"\n  },\n  "devDependencies": {\n    "typescript": "^5.3.0",\n    "@types/ws": "^8.5.10",\n    "@types/node": "^20.10.0",\n    "jest": "^29.7.0",\n    "ts-jest": "^29.1.0",\n    "@types/jest": "^29.5.0",\n    "eslint": "^8.56.0",\n    "ts-node": "^10.9.0"\n  }\n}`),
  f("tsconfig.json", "tsconfig.json", "json", `{\n  "compilerOptions": {\n    "target": "ES2022",\n    "module": "commonjs",\n    "outDir": "./dist",\n    "rootDir": "./src",\n    "strict": true,\n    "esModuleInterop": true,\n    "declaration": true,\n    "sourceMap": true,\n    "resolveJsonModule": true\n  },\n  "include": ["src/**/*"],\n  "exclude": ["node_modules", "dist", "tests"]\n}`),
  f("jest.config.ts", "jest.config.ts", "typescript", `export default {\n  preset: "ts-jest",\n  testEnvironment: "node",\n  roots: ["<rootDir>/tests"],\n  collectCoverageFrom: ["src/**/*.ts"],\n  coverageThreshold: {\n    global: { branches: 70, functions: 80, lines: 80, statements: 80 },\n  },\n};`),
  f(".gitignore", ".gitignore", "text", `node_modules/\ndist/\ncoverage/\n.env\n*.log\ndata/`),
  f("README.md", "README.md", "markdown", `# ZyraOS Blockchain\n\nA full blockchain implementation built from scratch in TypeScript by ZyraOS autonomous agents.\n\n## Features\n- SHA-256 block hashing with merkle trees\n- ECDSA digital signatures (secp256k1)\n- Proof-of-work consensus with difficulty adjustment\n- UTXO transaction model with fee estimation\n- HD wallet with encrypted keystore\n- Mempool with fee-priority ordering\n- WebSocket P2P networking with peer discovery\n- JSON-RPC server (12 endpoints)\n- LevelDB persistent storage\n- CLI with mining, wallet, and node management\n\n## Quick Start\n\`\`\`bash\nnpm install\nnpm run mine      # Start mining\nnpm test          # Run test suite\n\`\`\`\n\n## Architecture\n\`\`\`\nsrc/\n  core/        Block, Blockchain, Genesis\n  crypto/      SHA-256, ECDSA, Base58, Addresses\n  wallet/      HD keys, Keystore, UTXO selection\n  transaction/ Builder, Validator, Coinbase, Serializer\n  mining/      Miner, PoW, Difficulty adjustment\n  mempool/     Fee-priority queue, Orphan pool\n  network/     P2P server, Peer management, Discovery\n  rpc/         JSON-RPC server, 12 endpoint handlers\n  storage/     UTXO set, Block store, Chain state\n  cli/         Node startup, Argument parsing\n\`\`\`\n\n## Built by ZyraOS Agents\n- **Yami** — Task decomposition & planning\n- **Akira** — Architecture & core design\n- **Rei** — Implementation & coding\n- **Kira** — Testing & validation\n\n46 files | 4,218 lines | 32 tasks | 4 agents`),
];

function generateSha(): string {
  return Math.random().toString(16).slice(2, 9);
}

const DEMO_COMMITS: Omit<Commit, "timestamp">[] = [
  { sha: generateSha(), message: "feat: add TypeScript type definitions", description: "Block, Transaction, UTXO, Network, Config interfaces", agent: "Akira", files: ["src/types/block.ts", "src/types/transaction.ts", "src/types/network.ts", "src/types/config.ts"] },
  { sha: generateSha(), message: "feat: implement SHA-256, RIPEMD-160, merkle trees", description: "Double hashing, hash160, merkle root computation", agent: "Rei", files: ["src/crypto/hash.ts"] },
  { sha: generateSha(), message: "feat: add ECDSA keys, Base58, address derivation", description: "secp256k1 key pairs, Base58Check encoding, P2PKH addresses", agent: "Rei", files: ["src/crypto/keys.ts", "src/crypto/base58.ts", "src/crypto/address.ts"] },
  { sha: generateSha(), message: "feat: implement Block class with genesis config", description: "Block creation, hashing, genesis block, reward halving", agent: "Rei", files: ["src/core/block.ts", "src/core/genesis.ts"] },
  { sha: generateSha(), message: "feat: add Blockchain with difficulty adjustment", description: "Chain validation, block addition, 2016-block retargeting", agent: "Akira", files: ["src/core/blockchain.ts"] },
  { sha: generateSha(), message: "feat: implement PoW mining with coinbase rewards", description: "Mining loop, difficulty targeting, hash rate tracking", agent: "Rei", files: ["src/mining/miner.ts", "src/mining/pow.ts", "src/mining/difficulty.ts"] },
  { sha: generateSha(), message: "feat: build UTXO transaction system", description: "Transaction builder, validator, coinbase, serializer", agent: "Rei", files: ["src/transaction/builder.ts", "src/transaction/validator.ts", "src/transaction/coinbase.ts", "src/transaction/serializer.ts"] },
  { sha: generateSha(), message: "feat: implement HD wallet with encrypted keystore", description: "Key derivation, UTXO selection, balance tracking, AES-256 encryption", agent: "Akira", files: ["src/wallet/wallet.ts", "src/wallet/keystore.ts", "src/wallet/hdkey.ts"] },
  { sha: generateSha(), message: "feat: add mempool with fee-priority and eviction", description: "Fee-rate ordering, 300MB cap, orphan tracking, RBF support", agent: "Rei", files: ["src/mempool/mempool.ts", "src/mempool/orphans.ts"] },
  { sha: generateSha(), message: "feat: build P2P networking with peer discovery", description: "WebSocket server, peer scoring, message handling, seed nodes", agent: "Akira", files: ["src/network/server.ts", "src/network/peer.ts", "src/network/messages.ts", "src/network/discovery.ts"] },
  { sha: generateSha(), message: "feat: implement JSON-RPC server", description: "HTTP server, 12 endpoint handlers, error handling", agent: "Rei", files: ["src/rpc/server.ts", "src/rpc/handlers.ts"] },
  { sha: generateSha(), message: "feat: add persistent storage layer", description: "UTXO set, block store, chain state manager", agent: "Rei", files: ["src/storage/utxo.ts", "src/storage/blockstore.ts", "src/storage/chainstate.ts"] },
  { sha: generateSha(), message: "feat: create CLI with argument parsing", description: "Node startup, mining control, peer connections", agent: "Rei", files: ["src/cli/index.ts", "src/cli/args.ts"] },
  { sha: generateSha(), message: "test: add comprehensive test suites", description: "Crypto, chain, transaction, mempool, wallet, network tests", agent: "Kira", files: ["tests/crypto.test.ts", "tests/chain.test.ts", "tests/transaction.test.ts", "tests/mempool.test.ts", "tests/wallet.test.ts", "tests/network.test.ts"] },
  { sha: generateSha(), message: "chore: add project configuration", description: "Package.json, tsconfig, jest config, gitignore, README", agent: "Akira", files: ["package.json", "tsconfig.json", "jest.config.ts", ".gitignore", "README.md"] },
];

export { DEMO_MESSAGES, DEMO_FILES, DEMO_COMMITS };
