import type { FileNode, Commit } from "@/types";
export { DEMO_MESSAGES } from "./demo-messages";

const f = (name: string, path: string, lang: string, code: string): FileNode =>
  ({ name, path, type: "file", language: lang, content: code });

const d = (name: string, path: string, children: FileNode[]): FileNode =>
  ({ name, path, type: "directory", children });

const _placeholder = [
  { agent: "Yami", turn: 2, content: "Created 32 micro-tasks with dependency graph. Routing to agents based on complexity scoring." },
  { agent: "Akira", turn: 3, content: "[claude-opus-4-6] Designing core architecture. Establishing module boundaries: /src/core, /src/crypto, /src/wallet, /src/network, /src/rpc, /src/mempool, /src/mining, /src/storage, /src/cli." },
  { agent: "Akira", turn: 4, content: "Defined TypeScript interfaces — Block, BlockHeader, Transaction, UTXO, Peer, NetworkMessage, WalletState, RPCRequest, MempoolEntry.", codeBlock: { filename: "src/types/block.ts", language: "typescript", code: `export interface BlockHeader {\n  version: number;\n  previousHash: string;\n  merkleRoot: string;\n  timestamp: number;\n  difficulty: number;\n  nonce: number;\n}\n\nexport interface Block {\n  header: BlockHeader;\n  transactions: Transaction[];\n  hash: string;\n  height: number;\n}\n\nexport interface Transaction {\n  id: string;\n  inputs: TransactionInput[];\n  outputs: TransactionOutput[];\n  timestamp: number;\n  fee: number;\n}` } },
  { agent: "Rei", turn: 5, content: "[claude-sonnet-4-6] Implementing SHA-256 hashing utilities, RIPEMD-160 address derivation, and Base58Check encoding." },
  { agent: "Rei", turn: 6, content: "Completed crypto module — double SHA-256 for block headers, merkle root computation, address generation from public keys.", codeBlock: { filename: "src/crypto/hash.ts", language: "typescript", code: `import { createHash } from "crypto";\n\nexport function sha256(data: string | Buffer): string {\n  return createHash("sha256").update(data).digest("hex");\n}\n\nexport function doubleSha256(data: string | Buffer): string {\n  const first = createHash("sha256").update(data).digest();\n  return createHash("sha256").update(first).digest("hex");\n}\n\nexport function ripemd160(data: Buffer): string {\n  return createHash("ripemd160").update(data).digest("hex");\n}\n\nexport function merkleRoot(hashes: string[]): string {\n  if (hashes.length === 0) return sha256("");\n  if (hashes.length === 1) return hashes[0];\n  const next: string[] = [];\n  for (let i = 0; i < hashes.length; i += 2) {\n    const left = hashes[i];\n    const right = hashes[i + 1] || left;\n    next.push(doubleSha256(left + right));\n  }\n  return merkleRoot(next);\n}` } },
  { agent: "Rei", turn: 7, content: "[claude-sonnet-4-6] Building ECDSA digital signature system with secp256k1 curve and address derivation." },
  { agent: "Rei", turn: 8, content: "Completed keys.ts and address.ts — key pair generation, message signing, signature verification, public key to address conversion.", codeBlock: { filename: "src/crypto/keys.ts", language: "typescript", code: `import { generateKeyPairSync, sign, verify, createECDH } from "crypto";\n\nexport interface KeyPair {\n  publicKey: string;\n  privateKey: string;\n  address: string;\n}\n\nexport function generateKeyPair(): KeyPair {\n  const ecdh = createECDH("secp256k1");\n  ecdh.generateKeys();\n  const { publicKey, privateKey } = generateKeyPairSync("ec", {\n    namedCurve: "secp256k1",\n    publicKeyEncoding: { type: "spki", format: "pem" },\n    privateKeyEncoding: { type: "pkcs8", format: "pem" },\n  });\n  return { publicKey, privateKey, address: deriveAddress(publicKey) };\n}` } },
  { agent: "Akira", turn: 9, content: "[claude-opus-4-6] Implementing Block class with header hashing, genesis block factory, serialization, and merkle tree integration." },
  { agent: "Rei", turn: 10, content: "Completed Block and genesis module — constructor, calculateHash(), createGenesis(), fromJSON(), toBuffer() methods.", codeBlock: { filename: "src/core/block.ts", language: "typescript", code: `import { doubleSha256, merkleRoot } from "../crypto/hash";\nimport type { Block, BlockHeader, Transaction } from "../types/block";\n\nexport class BlockImpl implements Block {\n  header: BlockHeader;\n  transactions: Transaction[];\n  hash: string;\n  height: number;\n\n  constructor(header: BlockHeader, txs: Transaction[], height: number) {\n    this.header = header;\n    this.transactions = txs;\n    this.height = height;\n    this.header.merkleRoot = merkleRoot(txs.map(t => t.id));\n    this.hash = this.calculateHash();\n  }\n\n  calculateHash(): string {\n    return doubleSha256(JSON.stringify(this.header));\n  }\n\n  static createGenesis(): BlockImpl {\n    return new BlockImpl({\n      version: 1, previousHash: "0".repeat(64),\n      merkleRoot: "0".repeat(64), timestamp: 1700000000000,\n      difficulty: 4, nonce: 0,\n    }, [], 0);\n  }\n}` } },
  { agent: "Rei", turn: 11, content: "[claude-sonnet-4-6] Implementing chain validation, difficulty adjustment algorithm, and chain reorganization logic." },
  { agent: "Rei", turn: 12, content: "Chain module complete — block addition, hash linkage verification, longest chain selection, difficulty retargeting every 2016 blocks." },
  { agent: "Akira", turn: 13, content: "[claude-opus-4-6] Implementing proof-of-work consensus with adjustable difficulty and parallel nonce search." },
  { agent: "Rei", turn: 14, content: "Proof-of-work miner complete — mining loop with hash target, difficulty adjustment, coinbase reward halving.", codeBlock: { filename: "src/mining/miner.ts", language: "typescript", code: `import { BlockImpl } from "../core/block";\nimport type { BlockHeader, Transaction } from "../types/block";\nimport { Mempool } from "../mempool/mempool";\n\nexport class Miner {\n  private mining = false;\n  private mempool: Mempool;\n  private difficulty: number;\n\n  constructor(mempool: Mempool, difficulty: number) {\n    this.mempool = mempool;\n    this.difficulty = difficulty;\n  }\n\n  mine(previousHash: string, height: number, minerAddress: string): BlockImpl {\n    const txs = this.mempool.selectTransactions(1_000_000);\n    const coinbase = this.createCoinbase(minerAddress, height);\n    const allTxs = [coinbase, ...txs];\n    const target = "0".repeat(this.difficulty);\n    let nonce = 0;\n\n    while (true) {\n      const header: BlockHeader = {\n        version: 1, previousHash, merkleRoot: "",\n        timestamp: Date.now(), difficulty: this.difficulty, nonce,\n      };\n      const block = new BlockImpl(header, allTxs, height);\n      if (block.hash.startsWith(target)) return block;\n      nonce++;\n    }\n  }\n}` } },
  { agent: "Rei", turn: 15, content: "[claude-sonnet-4-6] Building UTXO transaction system with fee calculation, coinbase rewards, and script validation." },
  { agent: "Rei", turn: 16, content: "Transaction system complete — UTXO tracking, input/output linking, fee estimation, double-spend prevention, serialization." },
  { agent: "Akira", turn: 17, content: "[claude-opus-4-6] Implementing wallet module — HD key derivation, UTXO scanning, balance calculation, transaction building." },
  { agent: "Rei", turn: 18, content: "Wallet complete — key storage, address generation, UTXO selection (largest-first), change output handling, transaction signing." },
  { agent: "Akira", turn: 19, content: "[claude-opus-4-6] Building mempool with fee-priority ordering, size limits, transaction validation, and eviction policy." },
  { agent: "Rei", turn: 20, content: "Mempool complete — priority queue by fee rate, 300MB size cap, orphan transaction tracking, replacement-by-fee support." },
  { agent: "Akira", turn: 21, content: "[claude-opus-4-6] Designing P2P networking layer — peer discovery, block propagation, transaction relay, compact block protocol." },
  { agent: "Rei", turn: 22, content: "P2P networking complete — WebSocket connections, handshake protocol, inv/getdata messaging, peer scoring, ban list.", codeBlock: { filename: "src/network/peer.ts", language: "typescript", code: `import WebSocket from "ws";\nimport type { NetworkMessage } from "../types/network";\n\nexport class Peer {\n  readonly address: string;\n  readonly ws: WebSocket;\n  private score: number = 100;\n  private lastSeen: number = Date.now();\n\n  constructor(address: string, ws: WebSocket) {\n    this.address = address;\n    this.ws = ws;\n    this.setupHandlers();\n  }\n\n  send(msg: NetworkMessage): void {\n    if (this.ws.readyState === WebSocket.OPEN) {\n      this.ws.send(JSON.stringify(msg));\n    }\n  }\n\n  penalize(amount: number): void {\n    this.score = Math.max(0, this.score - amount);\n  }\n\n  get isBanned(): boolean {\n    return this.score <= 0;\n  }\n}` } },
  { agent: "Akira", turn: 23, content: "[claude-opus-4-6] Implementing JSON-RPC server — getblock, gettransaction, sendrawtransaction, getbalance, getpeerinfo endpoints." },
  { agent: "Rei", turn: 24, content: "RPC server complete — HTTP JSON-RPC 2.0 interface, authentication, rate limiting, 12 endpoint handlers." },
  { agent: "Rei", turn: 25, content: "[claude-sonnet-4-6] Building LevelDB storage layer — block index, UTXO set persistence, chain state, write batches." },
  { agent: "Rei", turn: 26, content: "Storage layer complete — block storage, UTXO database, chain tip tracking, atomic writes, pruning support." },
  { agent: "Rei", turn: 27, content: "[claude-sonnet-4-6] Implementing CLI interface — node startup, mining control, wallet management, peer connections, RPC client." },
  { agent: "Kira", turn: 28, content: "[claude-sonnet-4-6] Writing unit tests for crypto module — 18 test cases covering SHA-256, ECDSA, merkle trees, address derivation." },
  { agent: "Kira", turn: 29, content: "All crypto tests passing. Coverage: hash functions, key generation, signing, verification, address encoding, edge cases." },
  { agent: "Kira", turn: 30, content: "[claude-sonnet-4-6] Running integration tests — full chain lifecycle: genesis → mine → transact → validate → reorg → sync." },
  { agent: "Kira", turn: 31, content: "Integration tests passing. Validated: block mining, mempool eviction, chain reorg, peer sync, wallet balance, RPC endpoints, double-spend rejection." },
  { agent: "Yami", turn: 32, content: "All 32 tasks complete. Blockchain implementation ready — 46 files, 4,218 lines, full P2P stack with wallet, RPC, and storage." },
];

// 46 files across a deep project structure
const DEMO_FILES: FileNode[] = [
  d("src", "src", [
    d("core", "src/core", [
      f("block.ts", "src/core/block.ts", "typescript", `import { doubleSha256, merkleRoot } from "../crypto/hash";\nimport type { Block, BlockHeader, Transaction } from "../types/block";\n\nexport class BlockImpl implements Block {\n  header: BlockHeader;\n  transactions: Transaction[];\n  hash: string;\n  height: number;\n\n  constructor(header: BlockHeader, txs: Transaction[], height: number) {\n    this.header = header;\n    this.transactions = txs;\n    this.height = height;\n    this.header.merkleRoot = merkleRoot(txs.map(t => t.id));\n    this.hash = this.calculateHash();\n  }\n\n  calculateHash(): string {\n    return doubleSha256(JSON.stringify(this.header));\n  }\n\n  static createGenesis(): BlockImpl {\n    return new BlockImpl({ version: 1, previousHash: "0".repeat(64), merkleRoot: "0".repeat(64), timestamp: 1700000000000, difficulty: 4, nonce: 0 }, [], 0);\n  }\n\n  toJSON(): object {\n    return { header: this.header, transactions: this.transactions, hash: this.hash, height: this.height };\n  }\n}`),
      f("blockchain.ts", "src/core/blockchain.ts", "typescript", `import { BlockImpl } from "./block";\nimport { validateProofOfWork } from "../mining/pow";\nimport { UTXOSet } from "../storage/utxo";\n\nexport class Blockchain {\n  chain: BlockImpl[];\n  difficulty: number;\n  utxoSet: UTXOSet;\n\n  constructor() {\n    this.chain = [BlockImpl.createGenesis()];\n    this.difficulty = 4;\n    this.utxoSet = new UTXOSet();\n  }\n\n  getLatestBlock(): BlockImpl { return this.chain[this.chain.length - 1]; }\n  getBlockByHash(hash: string): BlockImpl | undefined { return this.chain.find(b => b.hash === hash); }\n  getBlockByHeight(h: number): BlockImpl | undefined { return this.chain[h]; }\n\n  addBlock(block: BlockImpl): boolean {\n    if (!this.isValidBlock(block)) return false;\n    this.chain.push(block);\n    this.utxoSet.applyBlock(block);\n    if (this.chain.length % 2016 === 0) this.adjustDifficulty();\n    return true;\n  }\n\n  isValidBlock(block: BlockImpl): boolean {\n    const prev = this.getLatestBlock();\n    if (block.header.previousHash !== prev.hash) return false;\n    if (!validateProofOfWork(block.hash, this.difficulty)) return false;\n    return block.hash === block.calculateHash();\n  }\n\n  adjustDifficulty(): void {\n    const last2016 = this.chain.slice(-2016);\n    const timespan = last2016[last2016.length - 1].header.timestamp - last2016[0].header.timestamp;\n    const expected = 2016 * 600000;\n    if (timespan < expected / 4) this.difficulty++;\n    else if (timespan > expected * 4) this.difficulty = Math.max(1, this.difficulty - 1);\n  }\n\n  isValidChain(): boolean {\n    for (let i = 1; i < this.chain.length; i++) {\n      if (!this.isValidBlock(this.chain[i])) return false;\n    }\n    return true;\n  }\n}`),
      f("genesis.ts", "src/core/genesis.ts", "typescript", `import { BlockImpl } from "./block";\n\nexport const GENESIS_BLOCK = BlockImpl.createGenesis();\n\nexport const GENESIS_HASH = GENESIS_BLOCK.hash;\n\nexport const NETWORK_MAGIC = Buffer.from("f9beb4d9", "hex");\n\nexport const MAX_BLOCK_SIZE = 4_000_000;\nexport const COINBASE_MATURITY = 100;\nexport const HALVING_INTERVAL = 210_000;\nexport const INITIAL_REWARD = 50_00000000;\n\nexport function getBlockReward(height: number): number {\n  const halvings = Math.floor(height / HALVING_INTERVAL);\n  if (halvings >= 64) return 0;\n  return Math.floor(INITIAL_REWARD / Math.pow(2, halvings));\n}`),
    ]),
    d("crypto", "src/crypto", [
      f("hash.ts", "src/crypto/hash.ts", "typescript", `import { createHash } from "crypto";\n\nexport function sha256(data: string | Buffer): string {\n  return createHash("sha256").update(data).digest("hex");\n}\n\nexport function doubleSha256(data: string | Buffer): string {\n  const first = createHash("sha256").update(data).digest();\n  return createHash("sha256").update(first).digest("hex");\n}\n\nexport function ripemd160(data: Buffer): string {\n  return createHash("ripemd160").update(data).digest("hex");\n}\n\nexport function hash160(data: Buffer): string {\n  const s = createHash("sha256").update(data).digest();\n  return createHash("ripemd160").update(s).digest("hex");\n}\n\nexport function merkleRoot(hashes: string[]): string {\n  if (hashes.length === 0) return sha256("");\n  if (hashes.length === 1) return hashes[0];\n  const next: string[] = [];\n  for (let i = 0; i < hashes.length; i += 2) {\n    const left = hashes[i];\n    const right = hashes[i + 1] || left;\n    next.push(doubleSha256(left + right));\n  }\n  return merkleRoot(next);\n}`),
      f("keys.ts", "src/crypto/keys.ts", "typescript", `import { generateKeyPairSync, sign, verify, createECDH } from "crypto";\nimport { hash160 } from "./hash";\nimport { encodeBase58Check } from "./base58";\n\nexport interface KeyPair {\n  publicKey: string;\n  privateKey: string;\n  address: string;\n}\n\nexport function generateKeyPair(): KeyPair {\n  const ecdh = createECDH("secp256k1");\n  ecdh.generateKeys();\n  const { publicKey, privateKey } = generateKeyPairSync("ec", {\n    namedCurve: "secp256k1",\n    publicKeyEncoding: { type: "spki", format: "pem" },\n    privateKeyEncoding: { type: "pkcs8", format: "pem" },\n  });\n  const address = deriveAddress(publicKey);\n  return { publicKey, privateKey, address };\n}\n\nexport function deriveAddress(publicKey: string): string {\n  const h = hash160(Buffer.from(publicKey));\n  return encodeBase58Check(Buffer.from("00" + h, "hex"));\n}\n\nexport function signMessage(msg: string, key: string): string {\n  return sign("sha256", Buffer.from(msg), key).toString("hex");\n}\n\nexport function verifySignature(msg: string, sig: string, key: string): boolean {\n  return verify("sha256", Buffer.from(msg), key, Buffer.from(sig, "hex"));\n}`),
      f("base58.ts", "src/crypto/base58.ts", "typescript", `const ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";\n\nexport function encodeBase58(buffer: Buffer): string {\n  let num = BigInt("0x" + buffer.toString("hex"));\n  let result = "";\n  while (num > 0n) {\n    const remainder = num % 58n;\n    num = num / 58n;\n    result = ALPHABET[Number(remainder)] + result;\n  }\n  for (const byte of buffer) {\n    if (byte !== 0) break;\n    result = "1" + result;\n  }\n  return result;\n}\n\nexport function encodeBase58Check(payload: Buffer): string {\n  const { sha256 } = require("./hash");\n  const checksum = sha256(sha256(payload.toString("hex"))).slice(0, 8);\n  return encodeBase58(Buffer.concat([payload, Buffer.from(checksum, "hex")]));\n}\n\nexport function decodeBase58(str: string): Buffer {\n  let num = 0n;\n  for (const char of str) {\n    num = num * 58n + BigInt(ALPHABET.indexOf(char));\n  }\n  const hex = num.toString(16).padStart(2, "0");\n  return Buffer.from(hex, "hex");\n}`),
      f("address.ts", "src/crypto/address.ts", "typescript", `import { hash160 } from "./hash";\nimport { encodeBase58Check, decodeBase58 } from "./base58";\n\nexport enum AddressType {\n  P2PKH = 0x00,\n  P2SH = 0x05,\n  TESTNET = 0x6f,\n}\n\nexport function publicKeyToAddress(pubKey: Buffer, type: AddressType = AddressType.P2PKH): string {\n  const h = hash160(pubKey);\n  const payload = Buffer.alloc(21);\n  payload[0] = type;\n  Buffer.from(h, "hex").copy(payload, 1);\n  return encodeBase58Check(payload);\n}\n\nexport function isValidAddress(address: string): boolean {\n  try {\n    const decoded = decodeBase58(address);\n    return decoded.length >= 25;\n  } catch {\n    return false;\n  }\n}\n\nexport function getAddressType(address: string): AddressType | null {\n  const decoded = decodeBase58(address);\n  const version = decoded[0];\n  if (version === 0x00) return AddressType.P2PKH;\n  if (version === 0x05) return AddressType.P2SH;\n  if (version === 0x6f) return AddressType.TESTNET;\n  return null;\n}`),
    ]),
    d("wallet", "src/wallet", [
      f("wallet.ts", "src/wallet/wallet.ts", "typescript", `import { generateKeyPair, KeyPair, signMessage } from "../crypto/keys";\nimport { createTransaction, Transaction } from "../transaction/builder";\nimport type { UTXO } from "../types/transaction";\n\nexport class Wallet {\n  private keys: KeyPair;\n  private utxos: UTXO[] = [];\n\n  constructor(existingKey?: KeyPair) {\n    this.keys = existingKey || generateKeyPair();\n  }\n\n  get address(): string { return this.keys.address; }\n  get publicKey(): string { return this.keys.publicKey; }\n\n  getBalance(): number {\n    return this.utxos.reduce((sum, u) => sum + u.amount, 0);\n  }\n\n  updateUTXOs(utxos: UTXO[]): void {\n    this.utxos = utxos.filter(u => u.address === this.address);\n  }\n\n  createTransaction(to: string, amount: number, fee: number): Transaction {\n    const selected = this.selectUTXOs(amount + fee);\n    const change = selected.reduce((s, u) => s + u.amount, 0) - amount - fee;\n    return createTransaction(selected, to, amount, this.address, change, this.keys);\n  }\n\n  private selectUTXOs(target: number): UTXO[] {\n    const sorted = [...this.utxos].sort((a, b) => b.amount - a.amount);\n    const selected: UTXO[] = [];\n    let total = 0;\n    for (const utxo of sorted) {\n      selected.push(utxo);\n      total += utxo.amount;\n      if (total >= target) break;\n    }\n    if (total < target) throw new Error("Insufficient funds");\n    return selected;\n  }\n}`),
      f("keystore.ts", "src/wallet/keystore.ts", "typescript", `import { readFileSync, writeFileSync, existsSync } from "fs";\nimport { createCipheriv, createDecipheriv, randomBytes, scryptSync } from "crypto";\nimport type { KeyPair } from "../crypto/keys";\n\nexport class Keystore {\n  private path: string;\n\n  constructor(path: string) {\n    this.path = path;\n  }\n\n  save(keys: KeyPair, password: string): void {\n    const salt = randomBytes(16);\n    const key = scryptSync(password, salt, 32);\n    const iv = randomBytes(16);\n    const cipher = createCipheriv("aes-256-gcm", key, iv);\n    const data = JSON.stringify(keys);\n    const encrypted = Buffer.concat([cipher.update(data, "utf8"), cipher.final()]);\n    const tag = cipher.getAuthTag();\n    writeFileSync(this.path, JSON.stringify({\n      salt: salt.toString("hex"), iv: iv.toString("hex"),\n      tag: tag.toString("hex"), data: encrypted.toString("hex"),\n    }));\n  }\n\n  load(password: string): KeyPair {\n    const raw = JSON.parse(readFileSync(this.path, "utf8"));\n    const key = scryptSync(password, Buffer.from(raw.salt, "hex"), 32);\n    const decipher = createDecipheriv("aes-256-gcm", key, Buffer.from(raw.iv, "hex"));\n    decipher.setAuthTag(Buffer.from(raw.tag, "hex"));\n    const decrypted = decipher.update(raw.data, "hex", "utf8") + decipher.final("utf8");\n    return JSON.parse(decrypted);\n  }\n\n  exists(): boolean { return existsSync(this.path); }\n}`),
      f("hdkey.ts", "src/wallet/hdkey.ts", "typescript", `import { createHmac } from "crypto";\nimport { generateKeyPair } from "../crypto/keys";\n\nexport class HDKey {\n  private seed: Buffer;\n  private chainCode: Buffer;\n\n  constructor(mnemonic: string) {\n    this.seed = createHmac("sha512", "zyraos-seed").update(mnemonic).digest();\n    this.chainCode = this.seed.subarray(32);\n  }\n\n  deriveChild(index: number) {\n    const data = Buffer.alloc(37);\n    this.seed.subarray(0, 33).copy(data);\n    data.writeUInt32BE(index, 33);\n    const I = createHmac("sha512", this.chainCode).update(data).digest();\n    return { key: I.subarray(0, 32), chainCode: I.subarray(32) };\n  }\n\n  derivePath(path: string) {\n    const segments = path.split("/").slice(1);\n    let current = this;\n    for (const seg of segments) {\n      const idx = parseInt(seg.replace("'", ""));\n      current.deriveChild(idx);\n    }\n    return current;\n  }\n}`),
    ]),
    d("transaction", "src/transaction", [
      f("builder.ts", "src/transaction/builder.ts", "typescript", `import { sha256 } from "../crypto/hash";\nimport { signMessage } from "../crypto/keys";\nimport type { Transaction, TransactionInput, TransactionOutput, UTXO } from "../types/transaction";\nimport type { KeyPair } from "../crypto/keys";\n\nexport type { Transaction };\n\nexport function createTransaction(\n  utxos: UTXO[], to: string, amount: number,\n  changeAddress: string, change: number, keys: KeyPair\n): Transaction {\n  const inputs: TransactionInput[] = utxos.map(u => ({\n    txId: u.txId, outputIndex: u.outputIndex,\n    signature: "", publicKey: keys.publicKey,\n  }));\n  const outputs: TransactionOutput[] = [\n    { address: to, amount },\n    ...(change > 0 ? [{ address: changeAddress, amount: change }] : []),\n  ];\n  const tx: Transaction = { id: "", inputs, outputs, timestamp: Date.now(), fee: 0 };\n  tx.id = sha256(JSON.stringify({ inputs, outputs, timestamp: tx.timestamp }));\n  tx.inputs = tx.inputs.map(i => ({ ...i, signature: signMessage(tx.id, keys.privateKey) }));\n  tx.fee = utxos.reduce((s, u) => s + u.amount, 0) - amount - change;\n  return tx;\n}`),
      f("validator.ts", "src/transaction/validator.ts", "typescript", `import { verifySignature } from "../crypto/keys";\nimport type { Transaction } from "../types/transaction";\nimport type { UTXOSet } from "../storage/utxo";\n\nexport function validateTransaction(tx: Transaction, utxoSet: UTXOSet): { valid: boolean; error?: string } {\n  if (tx.inputs.length === 0) return { valid: false, error: "No inputs" };\n  if (tx.outputs.length === 0) return { valid: false, error: "No outputs" };\n\n  let inputTotal = 0;\n  for (const input of tx.inputs) {\n    const utxo = utxoSet.get(input.txId, input.outputIndex);\n    if (!utxo) return { valid: false, error: "UTXO not found: " + input.txId };\n    if (!verifySignature(tx.id, input.signature, input.publicKey)) {\n      return { valid: false, error: "Invalid signature" };\n    }\n    inputTotal += utxo.amount;\n  }\n\n  const outputTotal = tx.outputs.reduce((s, o) => s + o.amount, 0);\n  if (outputTotal > inputTotal) return { valid: false, error: "Outputs exceed inputs" };\n  if (tx.outputs.some(o => o.amount < 0)) return { valid: false, error: "Negative output" };\n\n  return { valid: true };\n}`),
      f("coinbase.ts", "src/transaction/coinbase.ts", "typescript", `import { sha256 } from "../crypto/hash";\nimport { getBlockReward } from "../core/genesis";\nimport type { Transaction } from "../types/transaction";\n\nexport function createCoinbaseTransaction(minerAddress: string, height: number, fees: number): Transaction {\n  const reward = getBlockReward(height);\n  const tx: Transaction = {\n    id: "",\n    inputs: [{ txId: "0".repeat(64), outputIndex: 0xffffffff, signature: \`coinbase:\${height}\`, publicKey: "" }],\n    outputs: [{ address: minerAddress, amount: reward + fees }],\n    timestamp: Date.now(),\n    fee: 0,\n  };\n  tx.id = sha256(JSON.stringify(tx.inputs) + JSON.stringify(tx.outputs) + height);\n  return tx;\n}`),
      f("serializer.ts", "src/transaction/serializer.ts", "typescript", `import type { Transaction } from "../types/transaction";\n\nexport function serializeTransaction(tx: Transaction): Buffer {\n  const json = JSON.stringify(tx);\n  const buf = Buffer.alloc(4 + json.length);\n  buf.writeUInt32LE(json.length, 0);\n  buf.write(json, 4);\n  return buf;\n}\n\nexport function deserializeTransaction(buf: Buffer): Transaction {\n  const len = buf.readUInt32LE(0);\n  const json = buf.subarray(4, 4 + len).toString();\n  return JSON.parse(json);\n}\n\nexport function calculateTxSize(tx: Transaction): number {\n  return serializeTransaction(tx).length;\n}\n\nexport function calculateFeeRate(tx: Transaction): number {\n  const size = calculateTxSize(tx);\n  return tx.fee / size;\n}`),
    ]),
    d("mining", "src/mining", [
      f("miner.ts", "src/mining/miner.ts", "typescript", `import { BlockImpl } from "../core/block";\nimport type { BlockHeader } from "../types/block";\nimport { Mempool } from "../mempool/mempool";\nimport { createCoinbaseTransaction } from "../transaction/coinbase";\n\nexport class Miner {\n  private mempool: Mempool;\n  private difficulty: number;\n  private hashRate: number = 0;\n\n  constructor(mempool: Mempool, difficulty: number) {\n    this.mempool = mempool;\n    this.difficulty = difficulty;\n  }\n\n  mine(previousHash: string, height: number, minerAddress: string): BlockImpl {\n    const txs = this.mempool.selectTransactions(4_000_000);\n    const fees = txs.reduce((s, t) => s + t.fee, 0);\n    const coinbase = createCoinbaseTransaction(minerAddress, height, fees);\n    const target = "0".repeat(this.difficulty);\n    let nonce = 0;\n    const start = Date.now();\n\n    while (true) {\n      const header: BlockHeader = {\n        version: 1, previousHash, merkleRoot: "",\n        timestamp: Date.now(), difficulty: this.difficulty, nonce,\n      };\n      const block = new BlockImpl(header, [coinbase, ...txs], height);\n      if (block.hash.startsWith(target)) {\n        this.hashRate = nonce / ((Date.now() - start) / 1000);\n        return block;\n      }\n      nonce++;\n    }\n  }\n\n  getHashRate(): number { return this.hashRate; }\n}`),
      f("pow.ts", "src/mining/pow.ts", "typescript", `export function validateProofOfWork(hash: string, difficulty: number): boolean {\n  return hash.startsWith("0".repeat(difficulty));\n}\n\nexport function calculateTarget(difficulty: number): string {\n  return "0".repeat(difficulty) + "f".repeat(64 - difficulty);\n}\n\nexport function compareDifficulty(hash: string, target: string): boolean {\n  return BigInt("0x" + hash) <= BigInt("0x" + target);\n}`),
      f("difficulty.ts", "src/mining/difficulty.ts", "typescript", `export const TARGET_BLOCK_TIME = 600_000;\nexport const ADJUSTMENT_INTERVAL = 2016;\n\nexport function adjustDifficulty(currentDifficulty: number, timestamps: number[]): number {\n  if (timestamps.length < ADJUSTMENT_INTERVAL) return currentDifficulty;\n  const actualTime = timestamps[timestamps.length - 1] - timestamps[0];\n  const expectedTime = ADJUSTMENT_INTERVAL * TARGET_BLOCK_TIME;\n  const ratio = actualTime / expectedTime;\n\n  if (ratio < 0.25) return currentDifficulty + 1;\n  if (ratio > 4.0) return Math.max(1, currentDifficulty - 1);\n  return currentDifficulty;\n}`),
    ]),
    d("mempool", "src/mempool", [
      f("mempool.ts", "src/mempool/mempool.ts", "typescript", `import type { Transaction } from "../types/transaction";\nimport { calculateFeeRate } from "../transaction/serializer";\n\ninterface MempoolEntry {\n  tx: Transaction;\n  addedAt: number;\n  feeRate: number;\n}\n\nexport class Mempool {\n  private entries: Map<string, MempoolEntry> = new Map();\n  private maxSize = 300_000_000;\n  private currentSize = 0;\n\n  add(tx: Transaction): boolean {\n    if (this.entries.has(tx.id)) return false;\n    const feeRate = calculateFeeRate(tx);\n    this.entries.set(tx.id, { tx, addedAt: Date.now(), feeRate });\n    this.currentSize += JSON.stringify(tx).length;\n    if (this.currentSize > this.maxSize) this.evict();\n    return true;\n  }\n\n  remove(txId: string): void { this.entries.delete(txId); }\n  has(txId: string): boolean { return this.entries.has(txId); }\n  get size(): number { return this.entries.size; }\n\n  selectTransactions(maxSize: number): Transaction[] {\n    const sorted = [...this.entries.values()].sort((a, b) => b.feeRate - a.feeRate);\n    const selected: Transaction[] = [];\n    let size = 0;\n    for (const entry of sorted) {\n      const txSize = JSON.stringify(entry.tx).length;\n      if (size + txSize > maxSize) break;\n      selected.push(entry.tx);\n      size += txSize;\n    }\n    return selected;\n  }\n\n  private evict(): void {\n    const sorted = [...this.entries.entries()].sort((a, b) => a[1].feeRate - b[1].feeRate);\n    while (this.currentSize > this.maxSize * 0.75 && sorted.length > 0) {\n      const [id] = sorted.shift()!;\n      this.entries.delete(id);\n    }\n  }\n}`),
      f("orphans.ts", "src/mempool/orphans.ts", "typescript", `import type { Transaction } from "../types/transaction";\n\nexport class OrphanPool {\n  private orphans: Map<string, Transaction> = new Map();\n  private maxSize = 1000;\n\n  add(tx: Transaction): void {\n    if (this.orphans.size >= this.maxSize) {\n      const oldest = this.orphans.keys().next().value;\n      if (oldest) this.orphans.delete(oldest);\n    }\n    this.orphans.set(tx.id, tx);\n  }\n\n  getByParent(txId: string): Transaction[] {\n    return [...this.orphans.values()].filter(tx =>\n      tx.inputs.some(i => i.txId === txId)\n    );\n  }\n\n  remove(txId: string): void { this.orphans.delete(txId); }\n  get size(): number { return this.orphans.size; }\n}`),
    ]),
    d("network", "src/network", [
      f("server.ts", "src/network/server.ts", "typescript", `import WebSocket from "ws";\nimport { Peer } from "./peer";\nimport { MessageHandler } from "./messages";\nimport type { NetworkMessage } from "../types/network";\n\nexport class P2PServer {\n  private peers: Map<string, Peer> = new Map();\n  private server: WebSocket.Server | null = null;\n  private handler: MessageHandler;\n\n  constructor(handler: MessageHandler) {\n    this.handler = handler;\n  }\n\n  start(port: number): void {\n    this.server = new WebSocket.Server({ port });\n    this.server.on("connection", (ws, req) => {\n      const addr = req.socket.remoteAddress + ":" + req.socket.remotePort;\n      this.addPeer(addr, ws);\n    });\n  }\n\n  connectTo(address: string): void {\n    const ws = new WebSocket(\`ws://\${address}\`);\n    ws.on("open", () => this.addPeer(address, ws));\n  }\n\n  broadcast(msg: NetworkMessage): void {\n    this.peers.forEach(p => p.send(msg));\n  }\n\n  private addPeer(addr: string, ws: WebSocket): void {\n    const peer = new Peer(addr, ws);\n    this.peers.set(addr, peer);\n    ws.on("message", (data) => this.handler.handle(JSON.parse(data.toString()), peer));\n    ws.on("close", () => this.peers.delete(addr));\n  }\n\n  getPeerCount(): number { return this.peers.size; }\n  getPeers(): Peer[] { return [...this.peers.values()]; }\n}`),
      f("peer.ts", "src/network/peer.ts", "typescript", `import WebSocket from "ws";\nimport type { NetworkMessage } from "../types/network";\n\nexport class Peer {\n  readonly address: string;\n  readonly ws: WebSocket;\n  private score: number = 100;\n  private lastSeen: number = Date.now();\n  private version: string = "unknown";\n\n  constructor(address: string, ws: WebSocket) {\n    this.address = address;\n    this.ws = ws;\n  }\n\n  send(msg: NetworkMessage): void {\n    if (this.ws.readyState === WebSocket.OPEN) {\n      this.ws.send(JSON.stringify(msg));\n      this.lastSeen = Date.now();\n    }\n  }\n\n  penalize(amount: number): void { this.score = Math.max(0, this.score - amount); }\n  reward(amount: number): void { this.score = Math.min(200, this.score + amount); }\n  get isBanned(): boolean { return this.score <= 0; }\n  get isStale(): boolean { return Date.now() - this.lastSeen > 300_000; }\n  setVersion(v: string): void { this.version = v; }\n}`),
      f("messages.ts", "src/network/messages.ts", "typescript", `import type { NetworkMessage } from "../types/network";\nimport { Peer } from "./peer";\nimport type { Blockchain } from "../core/blockchain";\nimport type { Mempool } from "../mempool/mempool";\n\nexport class MessageHandler {\n  private chain: Blockchain;\n  private mempool: Mempool;\n\n  constructor(chain: Blockchain, mempool: Mempool) {\n    this.chain = chain;\n    this.mempool = mempool;\n  }\n\n  handle(msg: NetworkMessage, from: Peer): void {\n    switch (msg.type) {\n      case "BLOCK": this.handleBlock(msg.payload, from); break;\n      case "TX": this.handleTransaction(msg.payload, from); break;\n      case "SYNC_REQUEST": this.handleSyncRequest(msg.payload, from); break;\n      case "SYNC_RESPONSE": this.handleSyncResponse(msg.payload, from); break;\n      case "PEERS": this.handlePeers(msg.payload, from); break;\n      case "PING": from.send({ type: "PONG", payload: null }); break;\n      default: from.penalize(10);\n    }\n  }\n\n  private handleBlock(block: any, from: Peer): void {\n    if (this.chain.addBlock(block)) from.reward(1);\n    else from.penalize(5);\n  }\n\n  private handleTransaction(tx: any, from: Peer): void {\n    this.mempool.add(tx);\n  }\n\n  private handleSyncRequest(payload: any, from: Peer): void {\n    const blocks = this.chain.chain.slice(payload.fromHeight);\n    from.send({ type: "SYNC_RESPONSE", payload: blocks });\n  }\n\n  private handleSyncResponse(blocks: any[], from: Peer): void {\n    for (const block of blocks) this.chain.addBlock(block);\n  }\n\n  private handlePeers(_peers: any[], _from: Peer): void {}\n}`),
      f("discovery.ts", "src/network/discovery.ts", "typescript", `import { P2PServer } from "./server";\n\nconst SEED_NODES = [\n  "seed1.zyraos.net:6001",\n  "seed2.zyraos.net:6001",\n  "seed3.zyraos.net:6001",\n];\n\nexport class PeerDiscovery {\n  private server: P2PServer;\n  private known: Set<string> = new Set();\n  private maxPeers = 125;\n\n  constructor(server: P2PServer) {\n    this.server = server;\n  }\n\n  async bootstrap(): Promise<void> {\n    for (const seed of SEED_NODES) {\n      if (this.server.getPeerCount() >= this.maxPeers) break;\n      try { this.server.connectTo(seed); this.known.add(seed); }\n      catch { /* seed unavailable */ }\n    }\n  }\n\n  addKnown(address: string): void { this.known.add(address); }\n  getKnown(): string[] { return [...this.known]; }\n}`),
    ]),
    d("rpc", "src/rpc", [
      f("server.ts", "src/rpc/server.ts", "typescript", `import { createServer, IncomingMessage, ServerResponse } from "http";\nimport { handleRPC } from "./handlers";\nimport type { Blockchain } from "../core/blockchain";\nimport type { Mempool } from "../mempool/mempool";\n\nexport function startRPCServer(chain: Blockchain, mempool: Mempool, port: number): void {\n  const server = createServer((req: IncomingMessage, res: ServerResponse) => {\n    if (req.method !== "POST") {\n      res.writeHead(405).end();\n      return;\n    }\n    let body = "";\n    req.on("data", (chunk) => body += chunk);\n    req.on("end", () => {\n      try {\n        const request = JSON.parse(body);\n        const result = handleRPC(request, chain, mempool);\n        res.writeHead(200, { "Content-Type": "application/json" });\n        res.end(JSON.stringify({ jsonrpc: "2.0", id: request.id, result }));\n      } catch (err: any) {\n        res.writeHead(200, { "Content-Type": "application/json" });\n        res.end(JSON.stringify({ jsonrpc: "2.0", id: null, error: { code: -32600, message: err.message } }));\n      }\n    });\n  });\n  server.listen(port);\n}`),
      f("handlers.ts", "src/rpc/handlers.ts", "typescript", `import type { Blockchain } from "../core/blockchain";\nimport type { Mempool } from "../mempool/mempool";\n\ninterface RPCRequest {\n  method: string;\n  params: any[];\n  id: number;\n}\n\nexport function handleRPC(req: RPCRequest, chain: Blockchain, mempool: Mempool): any {\n  switch (req.method) {\n    case "getblockcount": return chain.chain.length;\n    case "getbestblockhash": return chain.getLatestBlock().hash;\n    case "getblock": return chain.getBlockByHash(req.params[0])?.toJSON();\n    case "getblockbyheight": return chain.getBlockByHeight(req.params[0])?.toJSON();\n    case "getmempoolinfo": return { size: mempool.size };\n    case "getdifficulty": return chain.difficulty;\n    case "sendrawtransaction": {\n      const tx = req.params[0];\n      mempool.add(tx);\n      return tx.id;\n    }\n    case "getpeerinfo": return { peers: 0 };\n    case "validatechain": return chain.isValidChain();\n    default: throw new Error("Method not found: " + req.method);\n  }\n}`),
    ]),
    d("storage", "src/storage", [
      f("utxo.ts", "src/storage/utxo.ts", "typescript", `import type { BlockImpl } from "../core/block";\nimport type { UTXO } from "../types/transaction";\n\nexport class UTXOSet {\n  private utxos: Map<string, UTXO> = new Map();\n\n  private key(txId: string, index: number): string {\n    return \`\${txId}:\${index}\`;\n  }\n\n  add(utxo: UTXO): void {\n    this.utxos.set(this.key(utxo.txId, utxo.outputIndex), utxo);\n  }\n\n  remove(txId: string, index: number): void {\n    this.utxos.delete(this.key(txId, index));\n  }\n\n  get(txId: string, index: number): UTXO | undefined {\n    return this.utxos.get(this.key(txId, index));\n  }\n\n  getByAddress(address: string): UTXO[] {\n    return [...this.utxos.values()].filter(u => u.address === address);\n  }\n\n  applyBlock(block: BlockImpl): void {\n    for (const tx of block.transactions) {\n      for (const input of tx.inputs) {\n        this.remove(input.txId, input.outputIndex);\n      }\n      tx.outputs.forEach((output, i) => {\n        this.add({ txId: tx.id, outputIndex: i, address: output.address, amount: output.amount });\n      });\n    }\n  }\n\n  get size(): number { return this.utxos.size; }\n}`),
      f("blockstore.ts", "src/storage/blockstore.ts", "typescript", `import type { BlockImpl } from "../core/block";\n\nexport class BlockStore {\n  private blocks: Map<string, BlockImpl> = new Map();\n  private heightIndex: Map<number, string> = new Map();\n\n  put(block: BlockImpl): void {\n    this.blocks.set(block.hash, block);\n    this.heightIndex.set(block.height, block.hash);\n  }\n\n  getByHash(hash: string): BlockImpl | undefined {\n    return this.blocks.get(hash);\n  }\n\n  getByHeight(height: number): BlockImpl | undefined {\n    const hash = this.heightIndex.get(height);\n    return hash ? this.blocks.get(hash) : undefined;\n  }\n\n  getLatestHeight(): number {\n    return Math.max(...this.heightIndex.keys(), 0);\n  }\n\n  has(hash: string): boolean { return this.blocks.has(hash); }\n  get size(): number { return this.blocks.size; }\n}`),
      f("chainstate.ts", "src/storage/chainstate.ts", "typescript", `export interface ChainState {\n  bestBlockHash: string;\n  bestHeight: number;\n  totalWork: bigint;\n  chainId: string;\n}\n\nexport class ChainStateManager {\n  private state: ChainState;\n\n  constructor() {\n    this.state = {\n      bestBlockHash: "0".repeat(64),\n      bestHeight: 0,\n      totalWork: 0n,\n      chainId: "zyraos-mainnet",\n    };\n  }\n\n  update(hash: string, height: number, work: bigint): void {\n    this.state.bestBlockHash = hash;\n    this.state.bestHeight = height;\n    this.state.totalWork += work;\n  }\n\n  get(): ChainState { return { ...this.state }; }\n  get bestHeight(): number { return this.state.bestHeight; }\n  get bestHash(): string { return this.state.bestBlockHash; }\n}`),
    ]),
    d("types", "src/types", [
      f("block.ts", "src/types/block.ts", "typescript", `export interface BlockHeader {\n  version: number;\n  previousHash: string;\n  merkleRoot: string;\n  timestamp: number;\n  difficulty: number;\n  nonce: number;\n}\n\nexport interface Block {\n  header: BlockHeader;\n  transactions: Transaction[];\n  hash: string;\n  height: number;\n}\n\nexport interface Transaction {\n  id: string;\n  inputs: TransactionInput[];\n  outputs: TransactionOutput[];\n  timestamp: number;\n  fee: number;\n}\n\nexport interface TransactionInput {\n  txId: string;\n  outputIndex: number;\n  signature: string;\n  publicKey: string;\n}\n\nexport interface TransactionOutput {\n  address: string;\n  amount: number;\n}`),
      f("transaction.ts", "src/types/transaction.ts", "typescript", `export type { Transaction, TransactionInput, TransactionOutput } from "./block";\n\nexport interface UTXO {\n  txId: string;\n  outputIndex: number;\n  address: string;\n  amount: number;\n}\n\nexport interface MempoolEntry {\n  tx: Transaction;\n  addedAt: number;\n  feeRate: number;\n  size: number;\n}`),
      f("network.ts", "src/types/network.ts", "typescript", `import type { Block, Transaction } from "./block";\n\nexport interface Peer {\n  address: string;\n  port: number;\n  lastSeen: number;\n  version: string;\n  score: number;\n}\n\nexport type NetworkMessage =\n  | { type: "BLOCK"; payload: Block }\n  | { type: "TX"; payload: Transaction }\n  | { type: "PEERS"; payload: Peer[] }\n  | { type: "SYNC_REQUEST"; payload: { fromHeight: number } }\n  | { type: "SYNC_RESPONSE"; payload: Block[] }\n  | { type: "PING"; payload: null }\n  | { type: "PONG"; payload: null }\n  | { type: "INV"; payload: { type: string; hash: string }[] }\n  | { type: "GETDATA"; payload: { type: string; hash: string }[] };`),
      f("config.ts", "src/types/config.ts", "typescript", `export interface NodeConfig {\n  network: "mainnet" | "testnet";\n  port: number;\n  rpcPort: number;\n  dataDir: string;\n  maxPeers: number;\n  miningEnabled: boolean;\n  minerAddress?: string;\n  logLevel: "debug" | "info" | "warn" | "error";\n  seedNodes: string[];\n}`),
    ]),
    d("cli", "src/cli", [
      f("index.ts", "src/cli/index.ts", "typescript", `import { Blockchain } from "../core/blockchain";\nimport { generateKeyPair } from "../crypto/keys";\nimport { P2PServer } from "../network/server";\nimport { MessageHandler } from "../network/messages";\nimport { PeerDiscovery } from "../network/discovery";\nimport { Mempool } from "../mempool/mempool";\nimport { Miner } from "../mining/miner";\nimport { startRPCServer } from "../rpc/server";\nimport { parseArgs } from "./args";\n\nconst args = parseArgs();\nconst chain = new Blockchain();\nconst mempool = new Mempool();\nconst keys = generateKeyPair();\nconst handler = new MessageHandler(chain, mempool);\nconst server = new P2PServer(handler);\nconst discovery = new PeerDiscovery(server);\n\nconsole.log("ZyraOS Blockchain Node v1.0.0");\nconsole.log("Address:", keys.address);\nconsole.log("Chain height:", chain.chain.length);\n\nserver.start(args.port || 6001);\nstartRPCServer(chain, mempool, args.rpcPort || 8332);\ndiscovery.bootstrap();\n\nif (args.mine) {\n  const miner = new Miner(mempool, chain.difficulty);\n  console.log("Mining enabled. Target difficulty:", chain.difficulty);\n}`),
      f("args.ts", "src/cli/args.ts", "typescript", `export interface CLIArgs {\n  port: number;\n  rpcPort: number;\n  mine: boolean;\n  connect?: string;\n  dataDir: string;\n}\n\nexport function parseArgs(): CLIArgs {\n  const args = process.argv.slice(2);\n  const result: CLIArgs = {\n    port: 6001, rpcPort: 8332, mine: false, dataDir: "./data",\n  };\n\n  for (let i = 0; i < args.length; i++) {\n    switch (args[i]) {\n      case "--port": result.port = parseInt(args[++i]); break;\n      case "--rpc-port": result.rpcPort = parseInt(args[++i]); break;\n      case "--mine": result.mine = true; break;\n      case "--connect": result.connect = args[++i]; break;\n      case "--datadir": result.dataDir = args[++i]; break;\n    }\n  }\n  return result;\n}`),
    ]),
  ]),
  d("tests", "tests", [
    f("crypto.test.ts", "tests/crypto.test.ts", "typescript", `import { sha256, doubleSha256, merkleRoot, hash160 } from "../src/crypto/hash";\nimport { generateKeyPair, signMessage, verifySignature } from "../src/crypto/keys";\nimport { encodeBase58, encodeBase58Check } from "../src/crypto/base58";\n\ndescribe("SHA-256", () => {\n  test("produces 64-char hex", () => expect(sha256("hello")).toHaveLength(64));\n  test("double hash differs", () => expect(doubleSha256("hello")).not.toBe(sha256("hello")));\n  test("merkle root of empty", () => expect(merkleRoot([])).toBeTruthy());\n  test("merkle root of one", () => expect(merkleRoot(["abc"])).toBe("abc"));\n  test("hash160 produces 40-char hex", () => expect(hash160(Buffer.from("test"))).toHaveLength(40));\n});\n\ndescribe("ECDSA", () => {\n  test("sign and verify", () => {\n    const kp = generateKeyPair();\n    const sig = signMessage("test", kp.privateKey);\n    expect(verifySignature("test", sig, kp.publicKey)).toBe(true);\n  });\n  test("reject wrong key", () => {\n    const kp1 = generateKeyPair();\n    const kp2 = generateKeyPair();\n    const sig = signMessage("test", kp1.privateKey);\n    expect(verifySignature("test", sig, kp2.publicKey)).toBe(false);\n  });\n});\n\ndescribe("Base58", () => {\n  test("encodes buffer", () => expect(encodeBase58(Buffer.from("hello"))).toBeTruthy());\n});`),
    f("chain.test.ts", "tests/chain.test.ts", "typescript", `import { Blockchain } from "../src/core/blockchain";\n\ndescribe("Blockchain", () => {\n  test("starts with genesis block", () => {\n    const chain = new Blockchain();\n    expect(chain.chain).toHaveLength(1);\n    expect(chain.chain[0].height).toBe(0);\n  });\n  test("validates chain integrity", () => {\n    const chain = new Blockchain();\n    expect(chain.isValidChain()).toBe(true);\n  });\n  test("rejects invalid block", () => {\n    const chain = new Blockchain();\n    expect(chain.chain.length).toBe(1);\n  });\n});`),
    f("transaction.test.ts", "tests/transaction.test.ts", "typescript", `import { createCoinbaseTransaction } from "../src/transaction/coinbase";\nimport { serializeTransaction, deserializeTransaction } from "../src/transaction/serializer";\n\ndescribe("Coinbase Transaction", () => {\n  test("creates valid coinbase", () => {\n    const tx = createCoinbaseTransaction("addr123", 0, 0);\n    expect(tx.id).toBeTruthy();\n    expect(tx.outputs[0].amount).toBeGreaterThan(0);\n  });\n});\n\ndescribe("Serialization", () => {\n  test("roundtrip", () => {\n    const tx = createCoinbaseTransaction("addr123", 0, 0);\n    const buf = serializeTransaction(tx);\n    const decoded = deserializeTransaction(buf);\n    expect(decoded.id).toBe(tx.id);\n  });\n});`),
    f("mempool.test.ts", "tests/mempool.test.ts", "typescript", `import { Mempool } from "../src/mempool/mempool";\n\ndescribe("Mempool", () => {\n  test("adds and retrieves transactions", () => {\n    const pool = new Mempool();\n    const tx = { id: "tx1", inputs: [], outputs: [], timestamp: Date.now(), fee: 1000 };\n    expect(pool.add(tx as any)).toBe(true);\n    expect(pool.size).toBe(1);\n    expect(pool.has("tx1")).toBe(true);\n  });\n  test("rejects duplicates", () => {\n    const pool = new Mempool();\n    const tx = { id: "tx1", inputs: [], outputs: [], timestamp: Date.now(), fee: 1000 };\n    pool.add(tx as any);\n    expect(pool.add(tx as any)).toBe(false);\n  });\n  test("selects by fee rate", () => {\n    const pool = new Mempool();\n    pool.add({ id: "low", inputs: [], outputs: [], timestamp: Date.now(), fee: 100 } as any);\n    pool.add({ id: "high", inputs: [], outputs: [], timestamp: Date.now(), fee: 10000 } as any);\n    const selected = pool.selectTransactions(100000);\n    expect(selected[0].id).toBe("high");\n  });\n});`),
    f("wallet.test.ts", "tests/wallet.test.ts", "typescript", `import { Wallet } from "../src/wallet/wallet";\n\ndescribe("Wallet", () => {\n  test("generates address", () => {\n    const wallet = new Wallet();\n    expect(wallet.address).toBeTruthy();\n  });\n  test("starts with zero balance", () => {\n    const wallet = new Wallet();\n    expect(wallet.getBalance()).toBe(0);\n  });\n});`),
    f("network.test.ts", "tests/network.test.ts", "typescript", `import { Peer } from "../src/network/peer";\n\ndescribe("Peer", () => {\n  test("bans after penalties", () => {\n    const mockWs = { readyState: 1, send: jest.fn() } as any;\n    const peer = new Peer("127.0.0.1:6001", mockWs);\n    expect(peer.isBanned).toBe(false);\n    peer.penalize(100);\n    expect(peer.isBanned).toBe(true);\n  });\n});`),
  ]),
  f("package.json", "package.json", "json", `{\n  "name": "zyraos-blockchain",\n  "version": "1.0.0",\n  "description": "A blockchain built from scratch by ZyraOS agents",\n  "scripts": {\n    "build": "tsc",\n    "start": "node dist/cli/index.js",\n    "dev": "ts-node src/cli/index.ts",\n    "test": "jest --coverage",\n    "mine": "ts-node src/cli/index.ts --mine",\n    "lint": "eslint src/ --ext .ts"\n  },\n  "dependencies": {\n    "ws": "^8.16.0",\n    "leveldown": "^6.1.0"\n  },\n  "devDependencies": {\n    "typescript": "^5.3.0",\n    "@types/ws": "^8.5.10",\n    "@types/node": "^20.10.0",\n    "jest": "^29.7.0",\n    "ts-jest": "^29.1.0",\n    "@types/jest": "^29.5.0",\n    "eslint": "^8.56.0",\n    "ts-node": "^10.9.0"\n  }\n}`),
  f("tsconfig.json", "tsconfig.json", "json", `{\n  "compilerOptions": {\n    "target": "ES2022",\n    "module": "commonjs",\n    "outDir": "./dist",\n    "rootDir": "./src",\n    "strict": true,\n    "esModuleInterop": true,\n    "declaration": true,\n    "sourceMap": true,\n    "resolveJsonModule": true\n  },\n  "include": ["src/**/*"],\n  "exclude": ["node_modules", "dist", "tests"]\n}`),
  f("jest.config.ts", "jest.config.ts", "typescript", `export default {\n  preset: "ts-jest",\n  testEnvironment: "node",\n  roots: ["<rootDir>/tests"],\n  collectCoverageFrom: ["src/**/*.ts"],\n  coverageThreshold: {\n    global: { branches: 70, functions: 80, lines: 80, statements: 80 },\n  },\n};`),
  f(".gitignore", ".gitignore", "text", `node_modules/\ndist/\ncoverage/\n.env\n*.log\ndata/`),
  f("README.md", "README.md", "markdown", `# ZyraOS Blockchain\n\nA full blockchain implementation built from scratch in TypeScript by ZyraOS autonomous agents.\n\n## Features\n- SHA-256 block hashing with merkle trees\n- ECDSA digital signatures (secp256k1)\n- Proof-of-work consensus with difficulty adjustment\n- UTXO transaction model with fee estimation\n- HD wallet with encrypted keystore\n- Mempool with fee-priority ordering\n- WebSocket P2P networking with peer discovery\n- JSON-RPC server (12 endpoints)\n- LevelDB persistent storage\n- CLI with mining, wallet, and node management\n\n## Quick Start\n\`\`\`bash\nnpm install\nnpm run mine      # Start mining\nnpm test          # Run test suite\n\`\`\`\n\n## Architecture\n\`\`\`\nsrc/\n  core/        Block, Blockchain, Genesis\n  crypto/      SHA-256, ECDSA, Base58, Addresses\n  wallet/      HD keys, Keystore, UTXO selection\n  transaction/ Builder, Validator, Coinbase, Serializer\n  mining/      Miner, PoW, Difficulty adjustment\n  mempool/     Fee-priority queue, Orphan pool\n  network/     P2P server, Peer management, Discovery\n  rpc/         JSON-RPC server, 12 endpoint handlers\n  storage/     UTXO set, Block store, Chain state\n  cli/         Node startup, Argument parsing\n\`\`\`\n\n## Built by ZyraOS Agents\n- **Yami** — Task decomposition & planning\n- **Akira** — Architecture & core design\n- **Rei** — Implementation & coding\n- **Kira** — Testing & validation\n\n46 files | 4,218 lines | 32 tasks | 4 agents`),
];

function generateSha(): string {
  return Math.random().toString(16).slice(2, 9);
}

// 312 commits — realistic incremental git history
const c = (msg: string, desc: string, agent: string, files: string[]) =>
  ({ sha: generateSha(), message: msg, description: desc, agent, files });

const DEMO_COMMITS: Omit<Commit, "timestamp">[] = [
  // Phase 1: Project scaffolding (1-12)
  c("chore: initialize project with npm init", "Create package.json with project metadata", "Akira", ["package.json"]),
  c("chore: add TypeScript configuration", "Strict mode, ES2022 target, declaration files", "Akira", ["tsconfig.json"]),
  c("chore: add jest configuration", "ts-jest preset, coverage thresholds", "Akira", ["jest.config.ts"]),
  c("chore: add gitignore", "Ignore node_modules, dist, coverage, .env, data", "Akira", [".gitignore"]),
  c("chore: install core dependencies", "ws, leveldown for networking and storage", "Akira", ["package.json"]),
  c("chore: install dev dependencies", "typescript, jest, ts-jest, eslint, ts-node", "Akira", ["package.json"]),
  c("chore: add npm scripts", "Build, start, dev, test, mine, lint commands", "Akira", ["package.json"]),
  c("chore: create src directory structure", "core, crypto, wallet, transaction, mining, mempool, network, rpc, storage, cli, types", "Akira", []),
  c("chore: create tests directory", "Set up test file structure", "Kira", []),
  c("docs: add initial README", "Project description, features list, quick start", "Akira", ["README.md"]),
  c("chore: add EditorConfig", "Consistent formatting across editors", "Akira", [".gitignore"]),
  c("chore: configure ESLint for TypeScript", "Strict rules, no-any warnings", "Akira", ["package.json"]),

  // Phase 2: Type definitions (13-24)
  c("feat: add BlockHeader interface", "version, previousHash, merkleRoot, timestamp, difficulty, nonce", "Akira", ["src/types/block.ts"]),
  c("feat: add Block interface", "header, transactions, hash, height fields", "Akira", ["src/types/block.ts"]),
  c("feat: add Transaction interface", "id, inputs, outputs, timestamp, fee", "Akira", ["src/types/block.ts"]),
  c("feat: add TransactionInput interface", "txId, outputIndex, signature, publicKey", "Akira", ["src/types/block.ts"]),
  c("feat: add TransactionOutput interface", "address, amount fields", "Akira", ["src/types/block.ts"]),
  c("feat: add UTXO type definition", "txId, outputIndex, address, amount", "Akira", ["src/types/transaction.ts"]),
  c("feat: add MempoolEntry type", "tx, addedAt, feeRate, size fields", "Akira", ["src/types/transaction.ts"]),
  c("feat: add Peer interface", "address, port, lastSeen, version, score", "Akira", ["src/types/network.ts"]),
  c("feat: add NetworkMessage union type", "BLOCK, TX, PEERS, SYNC_REQUEST, SYNC_RESPONSE, PING, PONG, INV, GETDATA", "Akira", ["src/types/network.ts"]),
  c("feat: add NodeConfig interface", "network, port, rpcPort, dataDir, maxPeers, mining settings", "Akira", ["src/types/config.ts"]),
  c("refactor: export Transaction types from transaction.ts", "Re-export from block.ts for cleaner imports", "Akira", ["src/types/transaction.ts"]),
  c("fix: make fee field required on Transaction", "Was optional, now required with default 0", "Akira", ["src/types/block.ts"]),

  // Phase 3: Crypto module (25-48)
  c("feat: implement sha256 function", "Single SHA-256 hash using Node crypto", "Rei", ["src/crypto/hash.ts"]),
  c("feat: implement doubleSha256 function", "Double SHA-256 for block header hashing", "Rei", ["src/crypto/hash.ts"]),
  c("feat: implement ripemd160 function", "RIPEMD-160 for address derivation", "Rei", ["src/crypto/hash.ts"]),
  c("feat: implement hash160 function", "SHA-256 followed by RIPEMD-160", "Rei", ["src/crypto/hash.ts"]),
  c("feat: implement merkle root computation", "Recursive pairwise hashing of transaction IDs", "Rei", ["src/crypto/hash.ts"]),
  c("test: add SHA-256 test vectors", "Known input/output pairs from NIST", "Kira", ["tests/crypto.test.ts"]),
  c("test: add double hash test", "Verify double differs from single", "Kira", ["tests/crypto.test.ts"]),
  c("test: add merkle root tests", "Empty, single, multiple leaf cases", "Kira", ["tests/crypto.test.ts"]),
  c("test: add hash160 test", "Verify 40-char hex output", "Kira", ["tests/crypto.test.ts"]),
  c("feat: implement secp256k1 key generation", "ECDSA key pair using Node crypto", "Rei", ["src/crypto/keys.ts"]),
  c("feat: implement message signing", "Sign with private key, return hex signature", "Rei", ["src/crypto/keys.ts"]),
  c("feat: implement signature verification", "Verify signature against public key", "Rei", ["src/crypto/keys.ts"]),
  c("feat: add address derivation from public key", "hash160 of pubkey with version prefix", "Rei", ["src/crypto/keys.ts"]),
  c("test: add ECDSA sign/verify test", "Generate keypair, sign, verify roundtrip", "Kira", ["tests/crypto.test.ts"]),
  c("test: add wrong key rejection test", "Verify signature fails with different key", "Kira", ["tests/crypto.test.ts"]),
  c("feat: implement Base58 encoding", "Bitcoin-style Base58 alphabet encoding", "Rei", ["src/crypto/base58.ts"]),
  c("feat: implement Base58Check encoding", "Base58 with 4-byte checksum suffix", "Rei", ["src/crypto/base58.ts"]),
  c("feat: implement Base58 decoding", "Reverse Base58 to buffer", "Rei", ["src/crypto/base58.ts"]),
  c("test: add Base58 encoding test", "Verify encodes buffer to string", "Kira", ["tests/crypto.test.ts"]),
  c("feat: add AddressType enum", "P2PKH (0x00), P2SH (0x05), TESTNET (0x6f)", "Rei", ["src/crypto/address.ts"]),
  c("feat: implement publicKeyToAddress", "Convert public key to Base58Check address", "Rei", ["src/crypto/address.ts"]),
  c("feat: implement address validation", "Check Base58 decode length", "Rei", ["src/crypto/address.ts"]),
  c("feat: implement getAddressType", "Parse version byte from address", "Rei", ["src/crypto/address.ts"]),
  c("fix: handle empty input in merkle root", "Return hash of empty string instead of crash", "Rei", ["src/crypto/hash.ts"]),

  // Phase 4: Block and chain (49-76)
  c("feat: implement BlockImpl constructor", "Set header, transactions, calculate hash", "Rei", ["src/core/block.ts"]),
  c("feat: implement calculateHash method", "doubleSha256 of JSON-serialized header", "Rei", ["src/core/block.ts"]),
  c("feat: implement createGenesis static method", "Hardcoded genesis block with zero hash", "Rei", ["src/core/block.ts"]),
  c("feat: add merkle root integration to Block", "Compute merkle root from transaction IDs on construction", "Rei", ["src/core/block.ts"]),
  c("feat: add toJSON serialization method", "Export block as plain object", "Rei", ["src/core/block.ts"]),
  c("feat: add block height tracking", "Height field set on construction", "Rei", ["src/core/block.ts"]),
  c("feat: define genesis block constants", "Network magic, max block size, coinbase maturity", "Akira", ["src/core/genesis.ts"]),
  c("feat: implement block reward calculation", "50 BTC initial, halving every 210,000 blocks", "Akira", ["src/core/genesis.ts"]),
  c("feat: implement halving schedule", "Reward drops to 0 after 64 halvings", "Akira", ["src/core/genesis.ts"]),
  c("test: verify genesis block creation", "Check height 0, valid hash", "Kira", ["tests/chain.test.ts"]),
  c("feat: implement Blockchain constructor", "Initialize with genesis block, difficulty 4", "Akira", ["src/core/blockchain.ts"]),
  c("feat: implement getLatestBlock", "Return last block in chain array", "Akira", ["src/core/blockchain.ts"]),
  c("feat: implement getBlockByHash", "Linear search for block matching hash", "Akira", ["src/core/blockchain.ts"]),
  c("feat: implement getBlockByHeight", "Direct array index lookup", "Akira", ["src/core/blockchain.ts"]),
  c("feat: implement addBlock with validation", "Check previous hash, PoW, recalculate hash", "Akira", ["src/core/blockchain.ts"]),
  c("feat: implement isValidBlock", "Verify hash linkage, proof-of-work, hash integrity", "Akira", ["src/core/blockchain.ts"]),
  c("feat: implement isValidChain", "Iterate all blocks and validate each", "Akira", ["src/core/blockchain.ts"]),
  c("feat: add UTXO set integration to blockchain", "Apply block transactions to UTXO set on add", "Akira", ["src/core/blockchain.ts"]),
  c("feat: implement difficulty adjustment", "Retarget every 2016 blocks based on actual vs expected time", "Akira", ["src/core/blockchain.ts"]),
  c("fix: clamp difficulty adjustment to 4x range", "Prevent extreme difficulty swings", "Akira", ["src/core/blockchain.ts"]),
  c("test: verify chain starts with genesis", "Check chain length is 1 after construction", "Kira", ["tests/chain.test.ts"]),
  c("test: verify chain validates correctly", "isValidChain returns true for fresh chain", "Kira", ["tests/chain.test.ts"]),
  c("test: verify invalid block rejection", "Block with wrong previous hash is rejected", "Kira", ["tests/chain.test.ts"]),
  c("refactor: extract block validation to separate method", "Cleaner separation of concerns", "Akira", ["src/core/blockchain.ts"]),
  c("fix: genesis timestamp should be deterministic", "Use fixed timestamp 1700000000000 instead of Date.now()", "Rei", ["src/core/block.ts"]),
  c("perf: cache latest block reference", "Avoid array access on every getLatestBlock call", "Rei", ["src/core/blockchain.ts"]),
  c("docs: add JSDoc comments to Block class", "Document constructor, calculateHash, createGenesis", "Akira", ["src/core/block.ts"]),

  // Phase 5: Mining (77-96)
  c("feat: implement validateProofOfWork", "Check hash starts with N zeros", "Rei", ["src/mining/pow.ts"]),
  c("feat: implement calculateTarget", "Convert difficulty to target hash string", "Rei", ["src/mining/pow.ts"]),
  c("feat: implement compareDifficulty", "BigInt comparison of hash vs target", "Rei", ["src/mining/pow.ts"]),
  c("feat: implement Miner constructor", "Accept mempool and difficulty", "Rei", ["src/mining/miner.ts"]),
  c("feat: implement mine method", "Select transactions, create coinbase, find valid nonce", "Rei", ["src/mining/miner.ts"]),
  c("feat: add hash rate tracking to miner", "Calculate hashes per second during mining", "Rei", ["src/mining/miner.ts"]),
  c("feat: integrate mempool transaction selection", "Select highest fee-rate transactions up to block size", "Rei", ["src/mining/miner.ts"]),
  c("feat: add coinbase transaction to mined blocks", "Block reward plus collected fees", "Rei", ["src/mining/miner.ts"]),
  c("feat: define TARGET_BLOCK_TIME constant", "600,000ms (10 minutes)", "Akira", ["src/mining/difficulty.ts"]),
  c("feat: define ADJUSTMENT_INTERVAL constant", "2016 blocks", "Akira", ["src/mining/difficulty.ts"]),
  c("feat: implement adjustDifficulty function", "Compare actual vs expected time, adjust up or down", "Akira", ["src/mining/difficulty.ts"]),
  c("fix: prevent difficulty going below 1", "Math.max(1, difficulty - 1)", "Rei", ["src/mining/difficulty.ts"]),
  c("fix: handle empty mempool in miner", "Mine block with only coinbase if mempool empty", "Rei", ["src/mining/miner.ts"]),
  c("perf: optimize nonce search loop", "Avoid re-serializing unchanged header fields", "Rei", ["src/mining/miner.ts"]),
  c("test: verify PoW validation", "Hash with correct prefix passes", "Kira", ["tests/chain.test.ts"]),
  c("test: verify PoW rejection", "Hash without correct prefix fails", "Kira", ["tests/chain.test.ts"]),
  c("refactor: move PoW validation to mining module", "Remove from blockchain, import from mining/pow", "Akira", ["src/core/blockchain.ts", "src/mining/pow.ts"]),
  c("fix: miner timestamp should be current time", "Use Date.now() not genesis timestamp", "Rei", ["src/mining/miner.ts"]),
  c("docs: document mining algorithm", "Add comments explaining nonce search and difficulty", "Akira", ["src/mining/miner.ts"]),
  c("feat: add getHashRate method to Miner", "Public accessor for hash rate metric", "Rei", ["src/mining/miner.ts"]),

  // Phase 6: Transactions (97-128)
  c("feat: implement createTransaction function", "Build transaction from UTXOs with inputs and outputs", "Rei", ["src/transaction/builder.ts"]),
  c("feat: add transaction signing", "Sign each input with private key", "Rei", ["src/transaction/builder.ts"]),
  c("feat: add transaction ID calculation", "SHA-256 of inputs, outputs, timestamp", "Rei", ["src/transaction/builder.ts"]),
  c("feat: add change output handling", "Return excess funds to sender address", "Rei", ["src/transaction/builder.ts"]),
  c("feat: add fee calculation", "Input total minus output total minus change", "Rei", ["src/transaction/builder.ts"]),
  c("feat: implement validateTransaction", "Check inputs exist, signatures valid, no overspend", "Rei", ["src/transaction/validator.ts"]),
  c("feat: add input existence check", "Verify each input references valid UTXO", "Rei", ["src/transaction/validator.ts"]),
  c("feat: add signature verification in validator", "Verify each input signature against public key", "Rei", ["src/transaction/validator.ts"]),
  c("feat: add overspend check", "Output total must not exceed input total", "Rei", ["src/transaction/validator.ts"]),
  c("feat: add negative output check", "Reject transactions with negative amounts", "Rei", ["src/transaction/validator.ts"]),
  c("feat: implement createCoinbaseTransaction", "Special transaction with block reward and fees", "Rei", ["src/transaction/coinbase.ts"]),
  c("feat: integrate block reward from genesis config", "getBlockReward(height) for coinbase amount", "Rei", ["src/transaction/coinbase.ts"]),
  c("feat: add coinbase input marker", "txId all zeros, outputIndex 0xffffffff", "Rei", ["src/transaction/coinbase.ts"]),
  c("feat: implement serializeTransaction", "Convert transaction to length-prefixed buffer", "Rei", ["src/transaction/serializer.ts"]),
  c("feat: implement deserializeTransaction", "Parse buffer back to Transaction object", "Rei", ["src/transaction/serializer.ts"]),
  c("feat: implement calculateTxSize", "Serialize and return byte length", "Rei", ["src/transaction/serializer.ts"]),
  c("feat: implement calculateFeeRate", "Fee divided by transaction size", "Rei", ["src/transaction/serializer.ts"]),
  c("test: verify coinbase creation", "Check valid ID and positive reward", "Kira", ["tests/transaction.test.ts"]),
  c("test: verify serialization roundtrip", "Serialize then deserialize, compare IDs", "Kira", ["tests/transaction.test.ts"]),
  c("test: verify fee rate calculation", "Check fee / size ratio", "Kira", ["tests/transaction.test.ts"]),
  c("fix: coinbase ID should include height", "Prevent duplicate IDs at same height", "Rei", ["src/transaction/coinbase.ts"]),
  c("fix: validator should return error details", "Return { valid, error } instead of boolean", "Rei", ["src/transaction/validator.ts"]),
  c("refactor: use typed return for validation", "Replace boolean with result object", "Rei", ["src/transaction/validator.ts"]),
  c("perf: avoid double serialization in fee rate", "Cache serialized size", "Rei", ["src/transaction/serializer.ts"]),
  c("fix: handle zero-input edge case", "Reject transactions with empty inputs array", "Rei", ["src/transaction/validator.ts"]),
  c("fix: handle zero-output edge case", "Reject transactions with empty outputs array", "Rei", ["src/transaction/validator.ts"]),
  c("docs: document UTXO transaction model", "Explain input/output linking in comments", "Akira", ["src/transaction/builder.ts"]),
  c("test: verify overspend rejection", "Transaction spending more than inputs should fail", "Kira", ["tests/transaction.test.ts"]),
  c("test: verify negative amount rejection", "Negative output amount should fail validation", "Kira", ["tests/transaction.test.ts"]),
  c("test: verify empty inputs rejection", "Transaction with no inputs should fail", "Kira", ["tests/transaction.test.ts"]),
  c("refactor: extract type exports from builder", "Re-export Transaction type for external use", "Akira", ["src/transaction/builder.ts"]),
  c("feat: add fee estimation helper", "Estimate fee based on input/output count", "Rei", ["src/transaction/builder.ts"]),

  // Phase 7: Wallet (129-152)
  c("feat: implement Wallet constructor", "Accept existing key pair or generate new", "Rei", ["src/wallet/wallet.ts"]),
  c("feat: add wallet address getter", "Return address from key pair", "Rei", ["src/wallet/wallet.ts"]),
  c("feat: add wallet public key getter", "Expose public key for transaction building", "Rei", ["src/wallet/wallet.ts"]),
  c("feat: implement getBalance", "Sum all UTXO amounts belonging to wallet", "Rei", ["src/wallet/wallet.ts"]),
  c("feat: implement updateUTXOs", "Filter global UTXO set for wallet address", "Rei", ["src/wallet/wallet.ts"]),
  c("feat: implement createTransaction in wallet", "Select UTXOs, build transaction, handle change", "Rei", ["src/wallet/wallet.ts"]),
  c("feat: implement UTXO selection algorithm", "Largest-first selection until target met", "Rei", ["src/wallet/wallet.ts"]),
  c("fix: throw on insufficient funds", "Error instead of creating invalid transaction", "Rei", ["src/wallet/wallet.ts"]),
  c("feat: implement Keystore constructor", "Accept file path for encrypted storage", "Akira", ["src/wallet/keystore.ts"]),
  c("feat: implement keystore save", "AES-256-GCM encryption with scrypt key derivation", "Akira", ["src/wallet/keystore.ts"]),
  c("feat: implement keystore load", "Decrypt and parse stored key pair", "Akira", ["src/wallet/keystore.ts"]),
  c("feat: add keystore exists check", "Check if file exists on disk", "Akira", ["src/wallet/keystore.ts"]),
  c("feat: add random salt generation", "16-byte random salt for each save", "Akira", ["src/wallet/keystore.ts"]),
  c("feat: add auth tag storage", "Store GCM auth tag for integrity verification", "Akira", ["src/wallet/keystore.ts"]),
  c("feat: implement HDKey constructor", "HMAC-SHA512 seed derivation from mnemonic", "Akira", ["src/wallet/hdkey.ts"]),
  c("feat: implement child key derivation", "BIP32-style hardened child derivation", "Akira", ["src/wallet/hdkey.ts"]),
  c("feat: implement path derivation", "Parse m/44'/0'/0' style paths", "Akira", ["src/wallet/hdkey.ts"]),
  c("test: verify wallet generates address", "New wallet should have non-empty address", "Kira", ["tests/wallet.test.ts"]),
  c("test: verify zero initial balance", "Fresh wallet should have 0 balance", "Kira", ["tests/wallet.test.ts"]),
  c("test: verify insufficient funds error", "Creating TX with no UTXOs should throw", "Kira", ["tests/wallet.test.ts"]),
  c("fix: wallet should sort UTXOs descending", "Largest first for optimal selection", "Rei", ["src/wallet/wallet.ts"]),
  c("fix: keystore should handle corrupt files", "Graceful error on decryption failure", "Akira", ["src/wallet/keystore.ts"]),
  c("perf: cache wallet balance", "Avoid recalculating on every getBalance call", "Rei", ["src/wallet/wallet.ts"]),
  c("docs: document wallet API", "JSDoc for constructor, getBalance, createTransaction", "Akira", ["src/wallet/wallet.ts"]),

  // Phase 8: Mempool (153-174)
  c("feat: implement Mempool constructor", "Initialize empty map, set 300MB max size", "Rei", ["src/mempool/mempool.ts"]),
  c("feat: implement mempool add", "Add transaction with fee rate calculation", "Rei", ["src/mempool/mempool.ts"]),
  c("feat: implement mempool remove", "Delete transaction by ID", "Rei", ["src/mempool/mempool.ts"]),
  c("feat: implement mempool has check", "Check if transaction exists in pool", "Rei", ["src/mempool/mempool.ts"]),
  c("feat: implement selectTransactions", "Sort by fee rate, select up to max block size", "Rei", ["src/mempool/mempool.ts"]),
  c("feat: implement mempool eviction", "Remove lowest fee-rate transactions when full", "Rei", ["src/mempool/mempool.ts"]),
  c("feat: add size tracking", "Track current mempool byte size", "Rei", ["src/mempool/mempool.ts"]),
  c("feat: reject duplicate transactions", "Return false if txId already in pool", "Rei", ["src/mempool/mempool.ts"]),
  c("feat: implement OrphanPool constructor", "Map with 1000 entry limit", "Rei", ["src/mempool/orphans.ts"]),
  c("feat: implement orphan add with eviction", "Remove oldest when at capacity", "Rei", ["src/mempool/orphans.ts"]),
  c("feat: implement getByParent lookup", "Find orphans referencing a specific transaction", "Rei", ["src/mempool/orphans.ts"]),
  c("feat: implement orphan removal", "Remove resolved orphan by ID", "Rei", ["src/mempool/orphans.ts"]),
  c("test: verify mempool add and retrieve", "Add transaction, check size and has", "Kira", ["tests/mempool.test.ts"]),
  c("test: verify duplicate rejection", "Same txId should return false on second add", "Kira", ["tests/mempool.test.ts"]),
  c("test: verify fee-rate priority selection", "Higher fee transactions selected first", "Kira", ["tests/mempool.test.ts"]),
  c("test: verify eviction on overflow", "Low-fee transactions evicted when pool is full", "Kira", ["tests/mempool.test.ts"]),
  c("fix: eviction should target 75% of max", "Evict until 75% capacity, not just one entry", "Rei", ["src/mempool/mempool.ts"]),
  c("fix: fee rate should handle zero-size edge case", "Prevent division by zero", "Rei", ["src/mempool/mempool.ts"]),
  c("perf: use sorted insertion instead of sort on select", "Maintain sorted order on add", "Rei", ["src/mempool/mempool.ts"]),
  c("refactor: extract fee rate calculation", "Import from transaction/serializer instead of inline", "Akira", ["src/mempool/mempool.ts"]),
  c("docs: document mempool eviction policy", "Explain fee-rate ordering and 300MB limit", "Akira", ["src/mempool/mempool.ts"]),
  c("feat: add replacement-by-fee support", "Replace existing tx if new one has higher fee", "Rei", ["src/mempool/mempool.ts"]),

  // Phase 9: Network (175-210)
  c("feat: implement P2PServer constructor", "Accept message handler dependency", "Akira", ["src/network/server.ts"]),
  c("feat: implement server start", "Create WebSocket.Server on specified port", "Akira", ["src/network/server.ts"]),
  c("feat: implement connectTo method", "Outbound WebSocket connection to peer", "Akira", ["src/network/server.ts"]),
  c("feat: implement broadcast method", "Send message to all connected peers", "Akira", ["src/network/server.ts"]),
  c("feat: implement addPeer helper", "Register peer, set up message and close handlers", "Akira", ["src/network/server.ts"]),
  c("feat: add getPeerCount method", "Return number of connected peers", "Akira", ["src/network/server.ts"]),
  c("feat: add getPeers method", "Return array of connected peer objects", "Akira", ["src/network/server.ts"]),
  c("feat: implement Peer constructor", "Store address, WebSocket, initial score", "Rei", ["src/network/peer.ts"]),
  c("feat: implement Peer send method", "Send JSON message if socket is open", "Rei", ["src/network/peer.ts"]),
  c("feat: implement peer scoring", "Penalize for bad behavior, reward for good", "Rei", ["src/network/peer.ts"]),
  c("feat: implement peer banning", "Ban when score reaches 0", "Rei", ["src/network/peer.ts"]),
  c("feat: add stale peer detection", "Mark peer stale after 5 minutes of inactivity", "Rei", ["src/network/peer.ts"]),
  c("feat: add peer version tracking", "Store protocol version string", "Rei", ["src/network/peer.ts"]),
  c("feat: implement MessageHandler constructor", "Accept blockchain and mempool references", "Akira", ["src/network/messages.ts"]),
  c("feat: implement message routing", "Switch on message type, dispatch to handlers", "Akira", ["src/network/messages.ts"]),
  c("feat: implement handleBlock", "Validate and add block, reward or penalize peer", "Akira", ["src/network/messages.ts"]),
  c("feat: implement handleTransaction", "Add transaction to mempool", "Akira", ["src/network/messages.ts"]),
  c("feat: implement handleSyncRequest", "Send blocks from requested height", "Akira", ["src/network/messages.ts"]),
  c("feat: implement handleSyncResponse", "Add received blocks to chain", "Akira", ["src/network/messages.ts"]),
  c("feat: implement handlePeers", "Process peer list from remote node", "Akira", ["src/network/messages.ts"]),
  c("feat: add PING/PONG handling", "Respond to pings for keepalive", "Akira", ["src/network/messages.ts"]),
  c("feat: penalize unknown message types", "Reduce peer score for invalid messages", "Akira", ["src/network/messages.ts"]),
  c("feat: define seed node list", "Three seed nodes for initial peer discovery", "Akira", ["src/network/discovery.ts"]),
  c("feat: implement PeerDiscovery constructor", "Accept P2P server reference", "Akira", ["src/network/discovery.ts"]),
  c("feat: implement bootstrap method", "Connect to seed nodes up to max peer limit", "Akira", ["src/network/discovery.ts"]),
  c("feat: add known peer tracking", "Maintain set of discovered peer addresses", "Akira", ["src/network/discovery.ts"]),
  c("feat: set max peers to 125", "Limit total connections for resource management", "Akira", ["src/network/discovery.ts"]),
  c("test: verify peer banning", "Penalize to 0 score, check isBanned", "Kira", ["tests/network.test.ts"]),
  c("test: verify peer send", "Mock WebSocket, verify send called", "Kira", ["tests/network.test.ts"]),
  c("fix: handle WebSocket close gracefully", "Remove peer from map on disconnect", "Rei", ["src/network/server.ts"]),
  c("fix: validate message JSON before parsing", "Catch parse errors, penalize peer", "Rei", ["src/network/messages.ts"]),
  c("fix: prevent self-connection", "Skip if address matches own address", "Akira", ["src/network/discovery.ts"]),
  c("perf: batch block sync responses", "Send blocks in chunks of 500", "Rei", ["src/network/messages.ts"]),
  c("refactor: extract peer management from server", "Cleaner separation of server and peer logic", "Akira", ["src/network/server.ts"]),
  c("docs: document P2P protocol messages", "Explain each message type and expected payload", "Akira", ["src/network/messages.ts"]),
  c("feat: add INV message handling", "Inventory announcement for new blocks/transactions", "Akira", ["src/network/messages.ts"]),

  // Phase 10: RPC (211-232)
  c("feat: implement RPC HTTP server", "Create server, handle POST requests", "Rei", ["src/rpc/server.ts"]),
  c("feat: add JSON-RPC 2.0 response format", "Wrap results with jsonrpc, id, result fields", "Rei", ["src/rpc/server.ts"]),
  c("feat: add error response format", "Return error code and message on failure", "Rei", ["src/rpc/server.ts"]),
  c("feat: reject non-POST requests", "Return 405 for GET, PUT, DELETE", "Rei", ["src/rpc/server.ts"]),
  c("feat: implement getblockcount handler", "Return chain length", "Rei", ["src/rpc/handlers.ts"]),
  c("feat: implement getbestblockhash handler", "Return latest block hash", "Rei", ["src/rpc/handlers.ts"]),
  c("feat: implement getblock handler", "Return block by hash as JSON", "Rei", ["src/rpc/handlers.ts"]),
  c("feat: implement getblockbyheight handler", "Return block by height as JSON", "Rei", ["src/rpc/handlers.ts"]),
  c("feat: implement getmempoolinfo handler", "Return mempool size", "Rei", ["src/rpc/handlers.ts"]),
  c("feat: implement getdifficulty handler", "Return current difficulty", "Rei", ["src/rpc/handlers.ts"]),
  c("feat: implement sendrawtransaction handler", "Add transaction to mempool, return txId", "Rei", ["src/rpc/handlers.ts"]),
  c("feat: implement getpeerinfo handler", "Return connected peer count", "Rei", ["src/rpc/handlers.ts"]),
  c("feat: implement validatechain handler", "Run full chain validation, return boolean", "Rei", ["src/rpc/handlers.ts"]),
  c("fix: handle malformed JSON in RPC body", "Return parse error instead of crash", "Rei", ["src/rpc/server.ts"]),
  c("fix: throw on unknown RPC method", "Return method not found error", "Rei", ["src/rpc/handlers.ts"]),
  c("feat: add RPC authentication", "Check API key header if configured", "Rei", ["src/rpc/server.ts"]),
  c("feat: add RPC rate limiting", "Max 100 requests per minute per IP", "Rei", ["src/rpc/server.ts"]),
  c("test: verify getblockcount returns chain length", "Fresh chain should return 1", "Kira", ["tests/chain.test.ts"]),
  c("perf: cache RPC responses for block queries", "Blocks are immutable, cache indefinitely", "Rei", ["src/rpc/handlers.ts"]),
  c("docs: document RPC endpoints", "List all methods with parameters and return types", "Akira", ["src/rpc/handlers.ts"]),
  c("refactor: use switch statement for RPC dispatch", "Replace if-else chain with switch", "Rei", ["src/rpc/handlers.ts"]),
  c("feat: add getbalance RPC handler", "Return balance for address from UTXO set", "Rei", ["src/rpc/handlers.ts"]),

  // Phase 11: Storage (233-256)
  c("feat: implement UTXOSet constructor", "Initialize empty Map", "Rei", ["src/storage/utxo.ts"]),
  c("feat: implement UTXO add method", "Store UTXO by txId:index key", "Rei", ["src/storage/utxo.ts"]),
  c("feat: implement UTXO remove method", "Delete UTXO by txId and index", "Rei", ["src/storage/utxo.ts"]),
  c("feat: implement UTXO get method", "Retrieve UTXO by txId and index", "Rei", ["src/storage/utxo.ts"]),
  c("feat: implement getByAddress method", "Filter all UTXOs for specific address", "Rei", ["src/storage/utxo.ts"]),
  c("feat: implement applyBlock method", "Remove spent UTXOs, add new outputs", "Rei", ["src/storage/utxo.ts"]),
  c("feat: add UTXO set size getter", "Return total number of unspent outputs", "Rei", ["src/storage/utxo.ts"]),
  c("feat: implement BlockStore constructor", "Maps for hash and height indexing", "Rei", ["src/storage/blockstore.ts"]),
  c("feat: implement block put method", "Store block, update height index", "Rei", ["src/storage/blockstore.ts"]),
  c("feat: implement getByHash method", "Direct Map lookup by block hash", "Rei", ["src/storage/blockstore.ts"]),
  c("feat: implement getByHeight method", "Two-step lookup via height index", "Rei", ["src/storage/blockstore.ts"]),
  c("feat: implement getLatestHeight", "Find max height in index", "Rei", ["src/storage/blockstore.ts"]),
  c("feat: add block existence check", "has method for quick lookup", "Rei", ["src/storage/blockstore.ts"]),
  c("feat: implement ChainStateManager", "Track best block hash, height, total work", "Rei", ["src/storage/chainstate.ts"]),
  c("feat: implement chainstate update", "Update best hash, height, accumulate work", "Rei", ["src/storage/chainstate.ts"]),
  c("feat: add chainstate getters", "bestHeight and bestHash accessors", "Rei", ["src/storage/chainstate.ts"]),
  c("feat: set chainId to zyraos-mainnet", "Identify network in chain state", "Rei", ["src/storage/chainstate.ts"]),
  c("fix: UTXO key should use colon separator", "Prevent collisions between txId and index", "Rei", ["src/storage/utxo.ts"]),
  c("fix: handle missing height index in BlockStore", "Return undefined instead of throwing", "Rei", ["src/storage/blockstore.ts"]),
  c("perf: use Map instead of object for UTXO storage", "Better performance for frequent add/remove", "Rei", ["src/storage/utxo.ts"]),
  c("test: verify UTXO add and retrieve", "Add UTXO, get by txId:index", "Kira", ["tests/transaction.test.ts"]),
  c("test: verify UTXO removal", "Remove UTXO, confirm get returns undefined", "Kira", ["tests/transaction.test.ts"]),
  c("refactor: rename private key method to key()", "Shorter internal method name", "Rei", ["src/storage/utxo.ts"]),
  c("docs: document storage layer architecture", "Explain UTXO set, block store, chain state", "Akira", ["src/storage/utxo.ts"]),

  // Phase 12: CLI (257-270)
  c("feat: implement CLI entry point", "Initialize blockchain, wallet, mempool, network, RPC", "Rei", ["src/cli/index.ts"]),
  c("feat: add startup banner", "Print ZyraOS version, address, chain height", "Rei", ["src/cli/index.ts"]),
  c("feat: start P2P server from CLI", "Listen on configured port", "Rei", ["src/cli/index.ts"]),
  c("feat: start RPC server from CLI", "Listen on configured RPC port", "Rei", ["src/cli/index.ts"]),
  c("feat: trigger peer discovery on startup", "Bootstrap connections to seed nodes", "Rei", ["src/cli/index.ts"]),
  c("feat: add mining flag to CLI", "Start miner if --mine flag passed", "Rei", ["src/cli/index.ts"]),
  c("feat: implement argument parser", "Parse --port, --rpc-port, --mine, --connect, --datadir", "Rei", ["src/cli/args.ts"]),
  c("feat: add default argument values", "Port 6001, RPC 8332, datadir ./data", "Rei", ["src/cli/args.ts"]),
  c("fix: handle missing argument values", "Skip if next arg is another flag", "Rei", ["src/cli/args.ts"]),
  c("feat: add --connect flag for initial peer", "Connect to specific peer on startup", "Rei", ["src/cli/index.ts"]),
  c("feat: print mining status on startup", "Show difficulty and mining enabled/disabled", "Rei", ["src/cli/index.ts"]),
  c("docs: add CLI usage to README", "Document all command line flags", "Akira", ["README.md"]),
  c("fix: handle port already in use error", "Graceful error message instead of crash", "Rei", ["src/cli/index.ts"]),
  c("feat: add --version flag", "Print version and exit", "Rei", ["src/cli/args.ts"]),

  // Phase 13: Integration tests and polish (271-312)
  c("test: add full mining integration test", "Mine block, verify chain accepts it", "Kira", ["tests/chain.test.ts"]),
  c("test: add transaction lifecycle test", "Create, sign, validate, add to mempool", "Kira", ["tests/transaction.test.ts"]),
  c("test: add wallet send integration test", "Create wallet, fund it, send transaction", "Kira", ["tests/wallet.test.ts"]),
  c("test: add peer connection test", "Connect two peers, verify handshake", "Kira", ["tests/network.test.ts"]),
  c("test: add block propagation test", "Mine block on node A, verify node B receives it", "Kira", ["tests/network.test.ts"]),
  c("test: add double-spend prevention test", "Spend same UTXO twice, verify second rejected", "Kira", ["tests/transaction.test.ts"]),
  c("test: add chain reorg test", "Longer chain replaces shorter chain", "Kira", ["tests/chain.test.ts"]),
  c("test: add mempool cleanup after block", "Transactions in block removed from mempool", "Kira", ["tests/mempool.test.ts"]),
  c("test: add coinbase maturity test", "Cannot spend coinbase until 100 blocks", "Kira", ["tests/transaction.test.ts"]),
  c("test: add difficulty adjustment test", "Verify difficulty changes after 2016 blocks", "Kira", ["tests/chain.test.ts"]),
  c("fix: race condition in peer message handling", "Lock message processing per peer", "Rei", ["src/network/messages.ts"]),
  c("fix: chain reorg should update UTXO set", "Roll back old UTXOs, apply new ones", "Rei", ["src/core/blockchain.ts"]),
  c("fix: memory leak in long-running miner", "Clear nonce buffer between attempts", "Rei", ["src/mining/miner.ts"]),
  c("fix: orphan pool should limit memory usage", "Evict oldest orphans when at capacity", "Rei", ["src/mempool/orphans.ts"]),
  c("fix: RPC should handle concurrent requests", "Queue requests to prevent state corruption", "Rei", ["src/rpc/server.ts"]),
  c("perf: optimize merkle root for large blocks", "Avoid array copy on each level", "Rei", ["src/crypto/hash.ts"]),
  c("perf: cache block hash after first calculation", "Avoid recalculating immutable hash", "Rei", ["src/core/block.ts"]),
  c("perf: use binary search for UTXO lookup by address", "Index UTXOs by address for faster queries", "Rei", ["src/storage/utxo.ts"]),
  c("perf: batch database writes in storage", "Group block + UTXO updates in single write batch", "Rei", ["src/storage/blockstore.ts"]),
  c("perf: optimize peer discovery round trips", "Parallel connection attempts to seed nodes", "Akira", ["src/network/discovery.ts"]),
  c("refactor: unify error handling across modules", "Consistent error types and messages", "Akira", ["src/core/blockchain.ts", "src/transaction/validator.ts"]),
  c("refactor: extract constants to genesis module", "All magic numbers in one place", "Akira", ["src/core/genesis.ts"]),
  c("refactor: simplify mempool eviction logic", "Cleaner while loop with explicit break", "Akira", ["src/mempool/mempool.ts"]),
  c("refactor: normalize peer address format", "Always use host:port string format", "Akira", ["src/network/peer.ts"]),
  c("docs: update README with architecture diagram", "ASCII diagram of module structure", "Akira", ["README.md"]),
  c("docs: add API reference for RPC endpoints", "Table with method, params, return type", "Akira", ["README.md"]),
  c("docs: document testing strategy", "Unit, integration, and coverage targets", "Kira", ["README.md"]),
  c("docs: add contributing guidelines", "Code style, PR process, test requirements", "Akira", ["README.md"]),
  c("chore: update dependencies to latest", "Bump ws, typescript, jest versions", "Akira", ["package.json"]),
  c("chore: add CI workflow placeholder", "GitHub Actions config for test and build", "Akira", [".gitignore"]),
  c("chore: bump version to 1.0.0", "First stable release", "Akira", ["package.json"]),
  c("feat: add line count tracking to README", "46 files, 4,218 lines, 32 tasks, 4 agents", "Yami", ["README.md"]),
];

export { DEMO_FILES, DEMO_COMMITS };
