import type { AgentMessage, FileNode, Commit } from "@/types";

// Realistic agent messages that simulate building a blockchain
const DEMO_MESSAGES: Omit<AgentMessage, "id" | "timestamp">[] = [
  { agent: "Yami", turn: 1, content: "Decomposing prompt into micro-tasks. Analyzing requirements: block structure, SHA-256 hashing, chain validation, proof-of-work, transactions, digital signatures, P2P networking, CLI." },
  { agent: "Yami", turn: 2, content: "Created 24 micro-tasks with dependency graph. Routing to agents based on complexity scoring." },
  { agent: "Akira", turn: 3, content: "[claude-opus-4-6] Designing core architecture. Establishing module boundaries: /src/block, /src/chain, /src/consensus, /src/transaction, /src/crypto, /src/network, /src/cli." },
  { agent: "Akira", turn: 4, content: "Defined TypeScript interfaces for Block, BlockHeader, Transaction, TransactionInput, TransactionOutput, Peer, and NetworkMessage types.", codeBlock: { filename: "src/types/block.ts", language: "typescript", code: `export interface BlockHeader {\n  version: number;\n  previousHash: string;\n  merkleRoot: string;\n  timestamp: number;\n  difficulty: number;\n  nonce: number;\n}\n\nexport interface Block {\n  header: BlockHeader;\n  transactions: Transaction[];\n  hash: string;\n}` } },
  { agent: "Rei", turn: 5, content: "[claude-sonnet-4-6] Implementing SHA-256 hashing utilities using Node.js crypto module." },
  { agent: "Rei", turn: 6, content: "Completed hash.ts — double SHA-256 for block headers, single SHA-256 for transaction IDs, merkle root computation.", codeBlock: { filename: "src/crypto/hash.ts", language: "typescript", code: `import { createHash } from "crypto";\n\nexport function sha256(data: string | Buffer): string {\n  return createHash("sha256").update(data).digest("hex");\n}\n\nexport function doubleSha256(data: string | Buffer): string {\n  const first = createHash("sha256").update(data).digest();\n  return createHash("sha256").update(first).digest("hex");\n}\n\nexport function merkleRoot(hashes: string[]): string {\n  if (hashes.length === 0) return sha256("");\n  if (hashes.length === 1) return hashes[0];\n  const next: string[] = [];\n  for (let i = 0; i < hashes.length; i += 2) {\n    const left = hashes[i];\n    const right = hashes[i + 1] || left;\n    next.push(doubleSha256(left + right));\n  }\n  return merkleRoot(next);\n}` } },
  { agent: "Rei", turn: 7, content: "[claude-sonnet-4-6] Building ECDSA digital signature system for transaction signing." },
  { agent: "Rei", turn: 8, content: "Completed keys.ts — secp256k1 key pair generation, message signing, signature verification.", codeBlock: { filename: "src/crypto/keys.ts", language: "typescript", code: `import { generateKeyPairSync, sign, verify } from "crypto";\n\nexport interface KeyPair {\n  publicKey: string;\n  privateKey: string;\n}\n\nexport function generateKeyPair(): KeyPair {\n  const { publicKey, privateKey } = generateKeyPairSync("ec", {\n    namedCurve: "secp256k1",\n    publicKeyEncoding: { type: "spki", format: "pem" },\n    privateKeyEncoding: { type: "pkcs8", format: "pem" },\n  });\n  return { publicKey, privateKey };\n}\n\nexport function signMessage(message: string, privateKey: string): string {\n  return sign("sha256", Buffer.from(message), privateKey).toString("hex");\n}\n\nexport function verifySignature(message: string, signature: string, publicKey: string): boolean {\n  return verify("sha256", Buffer.from(message), publicKey, Buffer.from(signature, "hex"));\n}` } },
  { agent: "Akira", turn: 9, content: "[claude-opus-4-6] Implementing Block class with SHA-256 header hashing, genesis block factory, and JSON serialization." },
  { agent: "Rei", turn: 10, content: "Completed Block implementation — constructor, calculateHash(), createGenesis(), fromJSON() methods.", codeBlock: { filename: "src/block/Block.ts", language: "typescript", code: `import { doubleSha256 } from "../crypto/hash";\nimport type { Block, BlockHeader, Transaction } from "../types/block";\n\nexport class BlockImpl implements Block {\n  header: BlockHeader;\n  transactions: Transaction[];\n  hash: string;\n\n  constructor(header: BlockHeader, transactions: Transaction[]) {\n    this.header = header;\n    this.transactions = transactions;\n    this.hash = this.calculateHash();\n  }\n\n  calculateHash(): string {\n    const data = JSON.stringify(this.header);\n    return doubleSha256(data);\n  }\n\n  static createGenesis(): BlockImpl {\n    const header: BlockHeader = {\n      version: 1,\n      previousHash: "0".repeat(64),\n      merkleRoot: "0".repeat(64),\n      timestamp: Date.now(),\n      difficulty: 1,\n      nonce: 0,\n    };\n    return new BlockImpl(header, []);\n  }\n}` } },
  { agent: "Rei", turn: 11, content: "[claude-sonnet-4-6] Implementing chain validation — verifying hash linkage, difficulty targets, and transaction integrity." },
  { agent: "Rei", turn: 12, content: "Chain validator complete. Checks: genesis block validity, hash continuity, proof-of-work difficulty, transaction signatures." },
  { agent: "Akira", turn: 13, content: "[claude-opus-4-6] Implementing proof-of-work consensus. Mining loop increments nonce until hash meets difficulty target." },
  { agent: "Rei", turn: 14, content: "Proof-of-work miner complete — adjustable difficulty, hash target comparison, mining reward distribution.", codeBlock: { filename: "src/consensus/proofOfWork.ts", language: "typescript", code: `import { BlockImpl } from "../block/Block";\nimport type { BlockHeader } from "../types/block";\n\nexport function mineBlock(header: BlockHeader, difficulty: number): { nonce: number; hash: string } {\n  const target = "0".repeat(difficulty);\n  let nonce = 0;\n  let hash = "";\n  \n  while (true) {\n    header.nonce = nonce;\n    const block = new BlockImpl(header, []);\n    hash = block.calculateHash();\n    if (hash.startsWith(target)) break;\n    nonce++;\n  }\n  \n  return { nonce, hash };\n}\n\nexport function validateProofOfWork(hash: string, difficulty: number): boolean {\n  return hash.startsWith("0".repeat(difficulty));\n}` } },
  { agent: "Rei", turn: 15, content: "[claude-sonnet-4-6] Building transaction system — UTXO model, input/output linking, coinbase transactions." },
  { agent: "Rei", turn: 16, content: "Transaction system complete. Supports: create, sign, verify, serialize, calculate fees." },
  { agent: "Kira", turn: 17, content: "[claude-sonnet-4-6] Writing unit tests for crypto module — hash functions, key generation, signature verification." },
  { agent: "Kira", turn: 18, content: "All crypto tests passing. 12 test cases: SHA-256 vectors, double hashing, merkle trees, ECDSA sign/verify, key pair generation." },
  { agent: "Akira", turn: 19, content: "[claude-opus-4-6] Designing P2P networking layer — WebSocket-based peer discovery, block propagation, transaction broadcast." },
  { agent: "Rei", turn: 20, content: "P2P networking complete — peer connections, handshake protocol, block/tx message types, gossip propagation.", codeBlock: { filename: "src/network/P2PServer.ts", language: "typescript", code: `import WebSocket from "ws";\nimport type { NetworkMessage, Peer } from "../types/block";\n\nexport class P2PServer {\n  private peers: Map<string, WebSocket> = new Map();\n  private port: number;\n  private server: WebSocket.Server | null = null;\n\n  constructor(port: number) {\n    this.port = port;\n  }\n\n  start(): void {\n    this.server = new WebSocket.Server({ port: this.port });\n    this.server.on("connection", (ws, req) => {\n      this.handleConnection(ws, req.socket.remoteAddress || "unknown");\n    });\n  }\n\n  connectToPeer(address: string): void {\n    const ws = new WebSocket(address);\n    ws.on("open", () => this.handleConnection(ws, address));\n  }\n\n  broadcast(message: NetworkMessage): void {\n    this.peers.forEach((ws) => ws.send(JSON.stringify(message)));\n  }\n}` } },
  { agent: "Rei", turn: 21, content: "[claude-sonnet-4-6] Implementing CLI interface — commands for mining, sending transactions, checking balance, listing peers." },
  { agent: "Kira", turn: 22, content: "[claude-sonnet-4-6] Running integration tests — full chain lifecycle: genesis → mine → transact → validate → sync." },
  { agent: "Kira", turn: 23, content: "Integration tests passing. Validated: block mining, chain sync between peers, transaction propagation, double-spend prevention." },
  { agent: "Yami", turn: 24, content: "All 24 tasks complete. Blockchain implementation ready — 18 source files, 6 test files, full P2P networking stack." },
];

// Realistic file tree
const DEMO_FILES: FileNode[] = [
  { name: "src", path: "src", type: "directory", children: [
    { name: "types", path: "src/types", type: "directory", children: [
      { name: "block.ts", path: "src/types/block.ts", type: "file", language: "typescript", content: `export interface BlockHeader {\n  version: number;\n  previousHash: string;\n  merkleRoot: string;\n  timestamp: number;\n  difficulty: number;\n  nonce: number;\n}\n\nexport interface Block {\n  header: BlockHeader;\n  transactions: Transaction[];\n  hash: string;\n}\n\nexport interface Transaction {\n  id: string;\n  inputs: TransactionInput[];\n  outputs: TransactionOutput[];\n  timestamp: number;\n}\n\nexport interface TransactionInput {\n  txId: string;\n  outputIndex: number;\n  signature: string;\n  publicKey: string;\n}\n\nexport interface TransactionOutput {\n  address: string;\n  amount: number;\n}\n\nexport interface Peer {\n  address: string;\n  port: number;\n  lastSeen: number;\n}\n\nexport type NetworkMessage =\n  | { type: "BLOCK"; payload: Block }\n  | { type: "TX"; payload: Transaction }\n  | { type: "PEERS"; payload: Peer[] }\n  | { type: "SYNC_REQUEST"; payload: { fromHeight: number } }\n  | { type: "SYNC_RESPONSE"; payload: Block[] };` },
    ]},
    { name: "crypto", path: "src/crypto", type: "directory", children: [
      { name: "hash.ts", path: "src/crypto/hash.ts", type: "file", language: "typescript", content: `import { createHash } from "crypto";\n\nexport function sha256(data: string | Buffer): string {\n  return createHash("sha256").update(data).digest("hex");\n}\n\nexport function doubleSha256(data: string | Buffer): string {\n  const first = createHash("sha256").update(data).digest();\n  return createHash("sha256").update(first).digest("hex");\n}\n\nexport function merkleRoot(hashes: string[]): string {\n  if (hashes.length === 0) return sha256("");\n  if (hashes.length === 1) return hashes[0];\n  const next: string[] = [];\n  for (let i = 0; i < hashes.length; i += 2) {\n    const left = hashes[i];\n    const right = hashes[i + 1] || left;\n    next.push(doubleSha256(left + right));\n  }\n  return merkleRoot(next);\n}` },
      { name: "keys.ts", path: "src/crypto/keys.ts", type: "file", language: "typescript", content: `import { generateKeyPairSync, sign, verify } from "crypto";\n\nexport interface KeyPair {\n  publicKey: string;\n  privateKey: string;\n}\n\nexport function generateKeyPair(): KeyPair {\n  const { publicKey, privateKey } = generateKeyPairSync("ec", {\n    namedCurve: "secp256k1",\n    publicKeyEncoding: { type: "spki", format: "pem" },\n    privateKeyEncoding: { type: "pkcs8", format: "pem" },\n  });\n  return { publicKey, privateKey };\n}\n\nexport function signMessage(msg: string, key: string): string {\n  return sign("sha256", Buffer.from(msg), key).toString("hex");\n}\n\nexport function verifySignature(msg: string, sig: string, key: string): boolean {\n  return verify("sha256", Buffer.from(msg), key, Buffer.from(sig, "hex"));\n}` },
    ]},
    { name: "block", path: "src/block", type: "directory", children: [
      { name: "Block.ts", path: "src/block/Block.ts", type: "file", language: "typescript", content: `import { doubleSha256 } from "../crypto/hash";\nimport type { Block, BlockHeader, Transaction } from "../types/block";\n\nexport class BlockImpl implements Block {\n  header: BlockHeader;\n  transactions: Transaction[];\n  hash: string;\n\n  constructor(header: BlockHeader, txs: Transaction[]) {\n    this.header = header;\n    this.transactions = txs;\n    this.hash = this.calculateHash();\n  }\n\n  calculateHash(): string {\n    return doubleSha256(JSON.stringify(this.header));\n  }\n\n  static createGenesis(): BlockImpl {\n    return new BlockImpl({\n      version: 1,\n      previousHash: "0".repeat(64),\n      merkleRoot: "0".repeat(64),\n      timestamp: Date.now(),\n      difficulty: 1,\n      nonce: 0,\n    }, []);\n  }\n}` },
    ]},
    { name: "chain", path: "src/chain", type: "directory", children: [
      { name: "Blockchain.ts", path: "src/chain/Blockchain.ts", type: "file", language: "typescript", content: `import { BlockImpl } from "../block/Block";\nimport { validateProofOfWork } from "../consensus/proofOfWork";\n\nexport class Blockchain {\n  chain: BlockImpl[];\n  difficulty: number;\n\n  constructor() {\n    this.chain = [BlockImpl.createGenesis()];\n    this.difficulty = 4;\n  }\n\n  getLatestBlock(): BlockImpl {\n    return this.chain[this.chain.length - 1];\n  }\n\n  addBlock(block: BlockImpl): boolean {\n    if (!this.isValidBlock(block)) return false;\n    this.chain.push(block);\n    return true;\n  }\n\n  isValidBlock(block: BlockImpl): boolean {\n    const prev = this.getLatestBlock();\n    if (block.header.previousHash !== prev.hash) return false;\n    if (!validateProofOfWork(block.hash, this.difficulty)) return false;\n    return block.hash === block.calculateHash();\n  }\n\n  isValidChain(): boolean {\n    for (let i = 1; i < this.chain.length; i++) {\n      if (!this.isValidBlock(this.chain[i])) return false;\n    }\n    return true;\n  }\n}` },
    ]},
    { name: "consensus", path: "src/consensus", type: "directory", children: [
      { name: "proofOfWork.ts", path: "src/consensus/proofOfWork.ts", type: "file", language: "typescript", content: `import { BlockImpl } from "../block/Block";\nimport type { BlockHeader } from "../types/block";\n\nexport function mineBlock(header: BlockHeader, difficulty: number): { nonce: number; hash: string } {\n  const target = "0".repeat(difficulty);\n  let nonce = 0;\n  let hash = "";\n  while (true) {\n    header.nonce = nonce;\n    const block = new BlockImpl(header, []);\n    hash = block.calculateHash();\n    if (hash.startsWith(target)) break;\n    nonce++;\n  }\n  return { nonce, hash };\n}\n\nexport function validateProofOfWork(hash: string, difficulty: number): boolean {\n  return hash.startsWith("0".repeat(difficulty));\n}` },
    ]},
    { name: "transaction", path: "src/transaction", type: "directory", children: [
      { name: "Transaction.ts", path: "src/transaction/Transaction.ts", type: "file", language: "typescript", content: `import { sha256 } from "../crypto/hash";\nimport { signMessage, verifySignature } from "../crypto/keys";\nimport type { Transaction, TransactionInput, TransactionOutput } from "../types/block";\n\nexport function createTransaction(\n  inputs: TransactionInput[],\n  outputs: TransactionOutput[]\n): Transaction {\n  const tx: Transaction = {\n    id: "",\n    inputs,\n    outputs,\n    timestamp: Date.now(),\n  };\n  tx.id = sha256(JSON.stringify(tx));\n  return tx;\n}\n\nexport function signTransaction(tx: Transaction, privateKey: string): Transaction {\n  tx.inputs = tx.inputs.map((input) => ({\n    ...input,\n    signature: signMessage(tx.id, privateKey),\n  }));\n  return tx;\n}\n\nexport function verifyTransaction(tx: Transaction): boolean {\n  return tx.inputs.every((input) =>\n    verifySignature(tx.id, input.signature, input.publicKey)\n  );\n}` },
    ]},
    { name: "network", path: "src/network", type: "directory", children: [
      { name: "P2PServer.ts", path: "src/network/P2PServer.ts", type: "file", language: "typescript", content: `import WebSocket from "ws";\nimport type { NetworkMessage } from "../types/block";\n\nexport class P2PServer {\n  private peers: Map<string, WebSocket> = new Map();\n  private port: number;\n\n  constructor(port: number) {\n    this.port = port;\n  }\n\n  start(): void {\n    const server = new WebSocket.Server({ port: this.port });\n    server.on("connection", (ws, req) => {\n      this.handleConnection(ws, req.socket.remoteAddress || "unknown");\n    });\n  }\n\n  connectToPeer(address: string): void {\n    const ws = new WebSocket(address);\n    ws.on("open", () => this.handleConnection(ws, address));\n  }\n\n  broadcast(msg: NetworkMessage): void {\n    this.peers.forEach((ws) => ws.send(JSON.stringify(msg)));\n  }\n\n  private handleConnection(ws: WebSocket, address: string): void {\n    this.peers.set(address, ws);\n    ws.on("message", (data) => this.handleMessage(data.toString(), address));\n    ws.on("close", () => this.peers.delete(address));\n  }\n\n  private handleMessage(raw: string, from: string): void {\n    const msg: NetworkMessage = JSON.parse(raw);\n    // Handle message types\n  }\n}` },
    ]},
    { name: "cli", path: "src/cli", type: "directory", children: [
      { name: "index.ts", path: "src/cli/index.ts", type: "file", language: "typescript", content: `import { Blockchain } from "../chain/Blockchain";\nimport { generateKeyPair } from "../crypto/keys";\nimport { P2PServer } from "../network/P2PServer";\n\nconst blockchain = new Blockchain();\nconst keys = generateKeyPair();\nconst server = new P2PServer(6001);\n\nconsole.log("ZyraOS Blockchain Node");\nconsole.log("Public Key:", keys.publicKey.slice(0, 64) + "...");\nconsole.log("Chain height:", blockchain.chain.length);\n\nserver.start();\nconsole.log("P2P server listening on port 6001");` },
    ]},
  ]},
  { name: "tests", path: "tests", type: "directory", children: [
    { name: "crypto.test.ts", path: "tests/crypto.test.ts", type: "file", language: "typescript", content: `import { sha256, doubleSha256, merkleRoot } from "../src/crypto/hash";\nimport { generateKeyPair, signMessage, verifySignature } from "../src/crypto/keys";\n\ndescribe("SHA-256", () => {\n  test("produces 64-char hex", () => {\n    expect(sha256("hello")).toHaveLength(64);\n  });\n  test("double hash differs from single", () => {\n    expect(doubleSha256("hello")).not.toBe(sha256("hello"));\n  });\n});\n\ndescribe("ECDSA", () => {\n  test("sign and verify", () => {\n    const kp = generateKeyPair();\n    const sig = signMessage("test", kp.privateKey);\n    expect(verifySignature("test", sig, kp.publicKey)).toBe(true);\n  });\n});` },
    { name: "chain.test.ts", path: "tests/chain.test.ts", type: "file", language: "typescript", content: `import { Blockchain } from "../src/chain/Blockchain";\nimport { BlockImpl } from "../src/block/Block";\n\ndescribe("Blockchain", () => {\n  test("starts with genesis block", () => {\n    const chain = new Blockchain();\n    expect(chain.chain).toHaveLength(1);\n  });\n  test("validates chain integrity", () => {\n    const chain = new Blockchain();\n    expect(chain.isValidChain()).toBe(true);\n  });\n});` },
  ]},
  { name: "package.json", path: "package.json", type: "file", language: "json", content: `{\n  "name": "zyraos-blockchain",\n  "version": "1.0.0",\n  "scripts": {\n    "build": "tsc",\n    "start": "node dist/cli/index.js",\n    "test": "jest",\n    "mine": "ts-node src/cli/index.ts"\n  },\n  "dependencies": {\n    "ws": "^8.16.0"\n  },\n  "devDependencies": {\n    "typescript": "^5.3.0",\n    "@types/ws": "^8.5.10",\n    "jest": "^29.7.0",\n    "ts-jest": "^29.1.0"\n  }\n}` },
  { name: "tsconfig.json", path: "tsconfig.json", type: "file", language: "json", content: `{\n  "compilerOptions": {\n    "target": "ES2022",\n    "module": "commonjs",\n    "outDir": "./dist",\n    "rootDir": "./src",\n    "strict": true,\n    "esModuleInterop": true,\n    "declaration": true\n  },\n  "include": ["src/**/*"]\n}` },
  { name: "README.md", path: "README.md", type: "file", language: "markdown", content: `# ZyraOS Blockchain\n\nA blockchain built from scratch in TypeScript by ZyraOS agents.\n\n## Features\n- SHA-256 block hashing with merkle trees\n- ECDSA digital signatures (secp256k1)\n- Proof-of-work consensus\n- UTXO transaction model\n- WebSocket P2P networking\n- CLI interface\n\n## Quick Start\n\`\`\`bash\nnpm install\nnpm run mine\n\`\`\`\n\n## Architecture\nBuilt by 4 autonomous agents:\n- **Yami** — Task decomposition & planning\n- **Akira** — Architecture & core design\n- **Rei** — Implementation & coding\n- **Kira** — Testing & validation` },
];

function generateSha(): string {
  return Math.random().toString(16).slice(2, 9);
}

const DEMO_COMMITS: Omit<Commit, "timestamp">[] = [
  { sha: generateSha(), message: "feat: add TypeScript type definitions", description: "Block, Transaction, Peer, NetworkMessage interfaces", agent: "Akira", files: ["src/types/block.ts"] },
  { sha: generateSha(), message: "feat: implement SHA-256 hashing utilities", description: "Single hash, double hash, merkle root computation", agent: "Rei", files: ["src/crypto/hash.ts"] },
  { sha: generateSha(), message: "feat: add ECDSA key pair generation and signing", description: "secp256k1 curve, PEM encoding, sign/verify", agent: "Rei", files: ["src/crypto/keys.ts"] },
  { sha: generateSha(), message: "feat: implement Block class with genesis factory", description: "Block creation, hash calculation, serialization", agent: "Rei", files: ["src/block/Block.ts"] },
  { sha: generateSha(), message: "feat: add Blockchain with chain validation", description: "Block addition, hash linkage verification, chain integrity", agent: "Akira", files: ["src/chain/Blockchain.ts"] },
  { sha: generateSha(), message: "feat: implement proof-of-work consensus", description: "Mining loop, difficulty targeting, PoW validation", agent: "Rei", files: ["src/consensus/proofOfWork.ts"] },
  { sha: generateSha(), message: "feat: build UTXO transaction system", description: "Create, sign, verify transactions with digital signatures", agent: "Rei", files: ["src/transaction/Transaction.ts"] },
  { sha: generateSha(), message: "feat: add P2P networking layer", description: "WebSocket server, peer connections, message broadcast", agent: "Akira", files: ["src/network/P2PServer.ts"] },
  { sha: generateSha(), message: "feat: create CLI interface", description: "Node startup, key generation, mining commands", agent: "Rei", files: ["src/cli/index.ts"] },
  { sha: generateSha(), message: "test: add crypto and chain test suites", description: "SHA-256 vectors, ECDSA sign/verify, chain integrity", agent: "Kira", files: ["tests/crypto.test.ts", "tests/chain.test.ts"] },
];

export { DEMO_MESSAGES, DEMO_FILES, DEMO_COMMITS };
